### ISSUE TITLE
No test file for sthv1,v2 and anet

### ISSUE THREAD

**Issue by HaihangWu** [OpenGVLab/UniFormerV2#15]
For these datasets, there are only run.sh files. For test files, can they be copied from run.sh with TRAIN.ENABLE False? So, the test file in sthv2 may look like this:

NUM_SHARDS=$SLURM_NNODES
NUM_GPUS=$WORLD_SIZE
BATCH_SIZE=128
BASE_LR=4e-5
work_path=./exp/sthv2/ssv2_b16_f16x224/
PYTHONPATH=$PYTHONPATH:./slowfast \
python tools/run_net_multi_node.py \
  --init_method tcp://localhost:10125 \
  --cfg $work_path/config.yaml \
  --num_shards $NUM_SHARDS \
  DATA.PATH_TO_DATA_DIR /data/gpfs/projects/punim0512/data/sth-sthv2/kc_label \
  DATA.PATH_PREFIX /data/gpfs/projects/punim0512/data/sth-sthv2/20bn-something-something-v2 \
  DATA.PATH_LABEL_SEPARATOR "," \
  TRAIN.EVAL_PERIOD 1 \
  TRAIN.CHECKPOINT_PERIOD 50 \
  TRAIN.BATCH_SIZE $BATCH_SIZE \
  TRAIN.SAVE_LATEST False \
  NUM_GPUS $NUM_GPUS \
  NUM_SHARDS $NUM_SHARDS \
  SOLVER.MAX_EPOCH 22 \
  SOLVER.BASE_LR $BASE_LR \
  SOLVER.BASE_LR_SCALE_NUM_SHARDS False \
  SOLVER.WARMUP_EPOCHS 5. \
  TRAIN.ENABLE False \
  DATA.TEST_CROP_SIZE 224 \
  TEST.NUM_ENSEMBLE_VIEWS 1 \
  TEST.NUM_SPATIAL_CROPS 3 \
  TEST.TEST_BEST True \
  DATA.MC True \
  RNG_SEED 6666 \
  OUTPUT_DIR $work_path

**Comment by HaihangWu** [comment]
I can see that run.sh will test the model performance automatically after the model train in sthv2 case. But the test results is like "logging.py:  99: json_stats: {"split": "test_final", "top1_acc": "0.60", "top5_acc": "2.91"}". Does it mean the top1_acc is 60% ? but how to interpret top5_acc?

**Comment by Andy1621** [comment]
The `top1_acc` and `top5_acc` is actually `0.60%` and `2.91%`. It seems that you do not load the pretrained model, thus you get the random prediction (1/174≈0.60%). To load the pretrained model, you have to set `TEST.CHECKPOINT_FILE_PATH`.

**Comment by zds-20181015** [comment]
> I can see that run.sh will test the model performance automatically after the model train in sthv2 case. But the test results is like "logging.py: 99: json_stats: {"split": "test_final", "top1_acc": "0.60", "top5_acc": "2.91"}". Does it mean the top1_acc is 60% ? but how to interpret top5_acc?

Hi, how do I load the pre-training model correctly, I set CHECKPOINT_FILE_PATH in the run.sh file, but it didn't work!

**Comment by Andy1621** [comment]
Can you provide your full `run.sh`?

**Comment by zds-20181015** [comment]
Thank you for your reply, here's the run.sh file I used for training.

NUM_SHARDS=1
NUM_GPUS=4
BATCH_SIZE=32
BASE_LR=1e-6
work_path=$(dirname $0)
PYTHONPATH=$PYTHONPATH:./slowfast 
python tools/run_net_multi_node.py 
  --init_method tcp://localhost:10125 
  --cfg $work_path/config.yaml 
  --num_shards $NUM_SHARDS 
  DATA.PATH_TO_DATA_DIR ./data_list/sthv1 
  DATA.PATH_PREFIX ./sthv1/20bn-something-something-v1 
  DATA.LABEL_PATH_TEMPLATE "somesomev1_rgb_{}_split.txt" 
  DATA.IMAGE_TEMPLATE "{:05d}.jpg" 
  TRAIN.EVAL_PERIOD 1 
  TRAIN.CHECKPOINT_PERIOD 50 
  TRAIN.BATCH_SIZE $BATCH_SIZE 
  TRAIN.SAVE_LATEST False 
  NUM_GPUS $NUM_GPUS 
  NUM_SHARDS $NUM_SHARDS 
  SOLVER.MAX_EPOCH 22 
  SOLVER.BASE_LR $BASE_LR 
  SOLVER.BASE_LR_SCALE_NUM_SHARDS False 
  SOLVER.WARMUP_EPOCHS 5. 
  DATA.TEST_CROP_SIZE 224 
  TEST.NUM_ENSEMBLE_VIEWS 1 
  TEST.NUM_SPATIAL_CROPS 3 
  TEST.TEST_BEST True 
  TEST.CHECKPOINT_FILE_PATH "./model/vit_b16.pth" 
  DATA.MC True 
  RNG_SEED 6666 
  OUTPUT_DIR $work_path

**Comment by Andy1621** [comment]
It seems that the model you loaded is CLIP pretraining. Please download the model from [MODEL_ZOO](https://github.com/OpenGVLab/UniFormerV2/blob/main/MODEL_ZOO.md) to reload it.
