### ISSUE TITLE
Error when performing evaluation/inference [MIT]

### ISSUE THREAD

**Issue by anjugopinath** [OpenGVLab/UniFormerV2#16]
I am trying to run evaluation.

I set **pretrained=False** in the function **uniformerv2_l14_336** in the file slowfast/models/uniformerv2_model.py

This is the command I executed:
./exp/mit/mit_l14_f8x336/test.sh

But, I am getting this error:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/4654298/209080254-4567024e-dab6-4941-b5c8-ccf386003e23.png">

Thank You

**Comment by Andy1621** [comment]
Since the code is for training, it will load Kinetics pretrained model. You can delete `cfg.UNIFORMERV2.PRETRAIN` in `config.yaml` if you only want to inference.

**Comment by anjugopinath** [comment]
Thanks, that fixed it.
