### ISSUE TITLE
Assertion error when trying to run evaluation/inference

### ISSUE THREAD

**Issue by anjugopinath** [OpenGVLab/UniFormerV2#17]
![image](https://user-images.githubusercontent.com/4654298/209206458-4a454247-96c7-494a-87ba-2e7dfbca5b77.png)

where line 109 is:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/4654298/209205466-2b2b9b34-fd8b-4fa9-a031-613095c9edc7.png">

Initially, I used print statements to debug, but nothing was being printed on the terminal. So, then I used logger as can be seen in line 108 in the above image.

Since the output of logger is sent to this file:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/4654298/209206142-f9674fc7-87c5-4cd7-a415-f95b46e289d7.png">

I checked the contents

As shown below, the path_label is not printed
<img width="924" alt="image" src="https://user-images.githubusercontent.com/4654298/209205811-95b3ce86-3e4a-4314-ba45-d445ed41d718.png">

So, I am not sure how to debug the error.

Why don't print statements work?

**Comment by Andy1621** [comment]
1. I'm not sure why your output is sent to *.pyc. If you follow the `test.sh`, it should be in the `$work_path`, i.e., `exp/mit/mit_l14_f8x336` and the file is `stdout.log`.
2. For the bug, I suggest you can have a look at the code and know what it means. 
Line 108 means that your label file is different from the default type. The default line should be `path,label`, and only two values are returned after `split()` function. You can see my label files [here](https://drive.google.com/drive/folders/17VB-XdF3Kfr9ORmnGyXCxTMs86n0L4QL). To fix the bug, you can change the code following your label files.

**Comment by anjugopinath** [comment]
The error was because for mit run.sh, the parameter DATA.PATH_LABEL_SEPARATOR was hard coded as ",". And I copied the same thing for test.sh.  I changed it to space.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/4654298/210418484-5ec1395c-be88-439c-b95d-d751abb8f44a.png">

Also, both logger and print statement outputs appear on the terminal (stdout) and not in stdout.log.
Figured this out later.

**Comment by anjugopinath** [comment]
To see the output of print statements and logging , I used sleep(time in seconds) (from time import sleep).
So, I put sleep() after the print statements so that the output was printed and only then did the program continue.

Also, you must give delimiter as " " (space). Comma does not work apparently. This is an issue with slowfast. 
See this link : https://github.com/facebookresearch/SlowFast/issues/119
Otherwise, you get "Failed to fetch video error"
