### ISSUE TITLE
Descriptions as ouput when running inference with test.sh (mit)

### ISSUE THREAD

**Issue by anjugopinath** [OpenGVLab/UniFormerV2#19]
How can I decode the video labels?

Below is the .pkl file generated on executing test.sh

<img width="763" alt="image" src="https://user-images.githubusercontent.com/4654298/210423764-8f38ce77-db06-4b54-b103-db2344096450.png">

I want the descriptions for each input. Currently, what I have is numeric labels.

**Comment by Andy1621** [comment]
Could you please provide the dataset you used? Then I can give you the label map.

**Comment by anjugopinath** [comment]
Hi Andy,

Thank You for your reply.
I tested it on COCO 2017 dataset. This is for a project I am working on and I want to test the pretrained MIT model on COCO.

Previously, I had tested using the Hugging Face site (https://huggingface.co/spaces/Andy1621/uniformerv2_demo) and had gotten satisfactory results.
Few examples are below:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/4654298/210699344-84444b78-1697-4fed-abdb-8467b4fce86f.png">

<img width="389" alt="image" src="https://user-images.githubusercontent.com/4654298/210699393-88facfb4-2dcf-4795-a234-4e02df59e6bd.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4654298/210699461-ba5669bf-5bed-4fb8-9710-be03a5317c15.png">

**Comment by Andy1621** [comment]
Thanks for your try. I have updated the label map in [Google Drive](https://drive.google.com/drive/folders/183xoSJAGKfxgMzzTngPUB_sIRdN-EagW). You can use the label map to get the corresponding labels.

**Comment by anjugopinath** [comment]
Hi Andy,

Thank you for uploading the label map. I am getting a label of 0 for all the 6 input images which corresponds to "clapping". But, none of the images are of clapping.
I will perform testing on more images to verify the performance. Especially since I got better results when testing on the Hugging Face website.

Meanwhile, I had another question on using the pretrained model.
Earlier, I had received this error 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/4654298/210881801-5e85b176-3ea0-4025-9c1f-20c83a5b07cc.png">

So, I set pretrained=False in this function https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/slowfast/models/uniformerv2_model.py#L449-L450

<img width="368" alt="image" src="https://user-images.githubusercontent.com/4654298/210888255-e1cb9c85-1102-4fed-a980-a805fa699635.png">

Is it possible that the performance could have worsened because of not using the CLIP pretrained model ?

Also, I am not sure I understand the below instruction 

"Follow extract_clip to extract visual encoder from CLIP."
The above sentence is under the subheading "Training" https://github.com/OpenGVLab/UniFormerV2/blob/main/INSTRUCTIONS.md

What is extract_clip?
Alternatively, could you provide the pretrained CLIP model for the mit dataset?

**Comment by Andy1621** [comment]
Thanks for your try! **I have checked the label map and found some errors**.
I have updated the label map in [Google Drive](https://drive.google.com/drive/folders/183xoSJAGKfxgMzzTngPUB_sIRdN-EagW). You can try the new version.

For your code, using `pretrained=False` is correct, and don't worry. The `extract_clip` is [here](https://github.com/OpenGVLab/UniFormerV2/tree/main/extract_clip).
**Note that there is any pretrained CLIP model for mit dataset**. If you use UniFormerV2 pretrained models, you don't need to use CLIP pretrained model.

I have built a [demo](https://huggingface.co/spaces/Andy1621/UniFormerV2_mit_demo) based on mit pretrained model, and it runs normally.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
