### ISSUE TITLE
加载clip的预训练模型

### ISSUE THREAD

**Issue by wntg** [OpenGVLab/UniFormerV2#2]
加载预训练模型的时候，clip的模型是pt后缀，为什么你用的是pth，想问下在哪下载的？
我修改了后缀名，加载clip的pt文件但是后面还是会报错。
_MODELS = {
    "ViT-B/16": os.path.join(MODEL_PATH, "ViT-B-16.pth"),
    "ViT-L/14": os.path.join(MODEL_PATH, "vit_l14.pth"),
    "ViT-L/14_336": os.path.join(MODEL_PATH, "vit_l14_336.pth"),
}

**Comment by wntg** [comment]
就是去哪里下载clip的图像encoder权重

**Comment by Andy1621** [comment]
Please follow the step in [INSTRUCTION](https://github.com/OpenGVLab/UniFormerV2/blob/main/INSTRUCTIONS.md). You have to use the code [here](https://github.com/OpenGVLab/UniFormerV2/blob/main/extract_clip/extract.ipynb) to generate the weight.
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/24236723/203508460-1095db4f-2145-472d-a363-c0fb4e56e30e.png">

**Comment by wntg** [comment]
Thanks for your response!  Thanks for your work!

**Comment by Andy1621** [comment]
Thanks for your try! As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.

**Comment by xwg0508** [comment]
请问在运行extract.ipynb文件时出现以下错误需要怎么解决呢
<img width="697" alt="image" src="https://github.com/OpenGVLab/UniFormerV2/assets/130576216/199aed59-0d4a-4409-90c0-c5e61fb411e8">
conda环境中clip已经安装了
<img width="548" alt="image" src="https://github.com/OpenGVLab/UniFormerV2/assets/130576216/9ebad3fe-d11c-416b-956c-7336883afc52">
