### ISSUE TITLE
Instruction for running on Multiple Nodes / Machines

### ISSUE THREAD

**Issue by vateye** [OpenGVLab/UniFormerV2#20]
Hi, are there any instructions for how to run the code on multiple machines or nodes? I did not see the configuration or starting command for running on multiple nodes. Thanks.

**Comment by Andy1621** [comment]
You can simply follow the scripts in my experiments. 
https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/exp/k400/k400%2Bk710_l14_f16x224/run.sh#L1-L29
In our training, we use `slurm` to start training before `python`
``` python3
srun -p video 
-n$NUM_SHARDS 
--gres=gpu:$NUM_GPUS 
--ntasks-per-node=1 
--cpus-per-task=$((NUM_CPU*NUM_GPUS)) \
--job-name ${JOB_NAME} \
python tools/run_net_multi_node.py \
......
```

**Comment by vateye** [comment]
Thanks for your reply. I am wondering how I can use master_port and master_addr to specify the multi-node training since I have no experience with slurm?

**Comment by Andy1621** [comment]
You do not need to set `master_port` and `master_addr `. It has been set in code
https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/tools/run_net_multi_node.py#L31-L33

**Comment by Andy1621** [comment]
Besides, you can also use `submitit` to run the process on multiple nodes.
The `TimeSformer` codebase, which is also based on SlowFast, provide some instructions [here](https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/tools/run_net_multi_node.py#L31-L33).

**Comment by Andy1621** [comment]
BTW, if you want to develop your research based on pretrained UniFormerV2, you can also follow my [PR](https://github.com/open-mmlab/mmaction2/pull/2153) for MMAction2. Thus you can use MMAction2 for multiple nodes.

**Comment by vateye** [comment]
Thank for your detailed answer!
