### ISSUE TITLE
finetune on self dataset

### ISSUE THREAD

**Issue by zhanghang-official** [OpenGVLab/UniFormerV2#22]
您好，感谢您的工作。
我想用UniformerV2训练自己的数据集，我想确认下我的想法是否正确：
1、有两种加载预训练模型方式，一种是加载clip-vit预训练模型不加载uniformerv2预训练模型，一种是加载uniformerv2预训练模型不加载clip-vit预训练模型。可以同时加载clip-vit预训练模型和uniformerv2预训练模型吗？
2、加载clip-vit预训练模型时 MODEL.USE_CHECKPOINT 和 MODEL.CHECKPOINT_NUM 具体是什么意思呢？

**Comment by Andy1621** [comment]
1. UniFormerV2是基于CLIP预训练的，加载UniFormerV2的模型会自动覆盖CLIP预训练。对于你的数据集，如果是日常行为相关的并且与Kinetics数据集相似的话，建议你使用UniFormerV2的预训练，且只需要使用global模块；如果是运动相关的，与something-something数据集相似，更多是物体和物体之间的交互，建议使用CLIP-ViT预训练，同时使用global和local模块。参考相关的config即可。
2. MODEL.USE_CHECKPOINT和MODEL.CHECKPOINT_NUM为torch.utils.checkpoint相关参数，使用checkpoint减小forward时存储中间变量的显存开销，从而可以跑更大的batch。如果你的显存足够大，直接设置MODEL.USE_CHECKPOINT为False就好。

**Comment by zhanghang-official** [comment]
明白了，感谢。

**Comment by snowkueen** [comment]
> 1. UniFormerV2是基于CLIP预训练的，加载UniFormerV2的模型会自动覆盖CLIP预训练。对于你的数据集，如果是日常行为相关的并且与Kinetics数据集相似的话，建议你使用UniFormerV2的预训练，且只需要使用global模块；如果是运动相关的，与something-something数据集相似，更多是物体和物体之间的交互，建议使用CLIP-ViT预训练，同时使用global和local模块。参考相关的config即可。
> 2. MODEL.USE_CHECKPOINT和MODEL.CHECKPOINT_NUM为torch.utils.checkpoint相关参数，使用checkpoint减小forward时存储中间变量的显存开销，从而可以跑更大的batch。如果你的显存足够大，直接设置MODEL.USE_CHECKPOINT为False就好。

请问，抽烟和扔东西算日常行为还是交互行为，应该用哪个预训练模型？还有无法下载something-something的预训练模型，能麻烦提供下吗？
