### ISSUE TITLE
Can you share kinetics-400 train data?

### ISSUE THREAD

**Issue by JeonDF** [OpenGVLab/UniFormerV2#25]
``` 
Hi! I have uploaded one copy of my Kineti400 to BaiduYun.
Link: https://pan.baidu.com/s/1sOTjfryT1j6BmA9MOqbl9w  Password: 6jb5

_Originally posted by @Andy1621 in https://github.com/OpenGVLab/UniFormerV2/issues/13#issuecomment-1356622469_
```

Can you re-share the file from the link above that you previously shared(in issue#13)? 
The link is invalid now.

There is many invalid video files (fail to load) in final test process.
I used video files of kinetics-400 archive  from amazon storage.
(ex> https://s3.amazonaws.com/kinetics/400/test/part_0.tar.gz)

There was the file of 'replacement_for_corrupted_k400' in archive files and I replaced video files in the compressed file.
Nevertheless, there was many invalid video file (fail to load).

I can find invalid video files only through error message .
(ex>
```
File "/UniFormerV2/slowfast/datasets/kinetics_sparse.py", line 336, in __getitem__
    raise RuntimeError(
RuntimeError: Failed to load video idx 64251 from /datasets/kinetics-400/videos/I0luMKjIZyg.mp4 after 10 retries
```
/datasets/kinetics-400/videos/**_I0luMKjIZyg.mp4_**
)

It takes so much time to find invalid video files in final test process.

So stressful. 
Is there any way to find out Invalid video files before executing test process?

**Comment by Andy1621** [comment]
Thanks for your question. You can download it from my sharing.

URL: https://pan.baidu.com/s/1BC-Lwu1F1655-DVfUp3pYg
Password: 3hhh

**Comment by JeonDF** [comment]
Thank you so much for your sharing 😊
