### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by 22222222z** [OpenGVLab/UniFormerV2#26]
run_net_multi_node.py: error: unrecognized arguments: DATA.PATH_TO_DATA_DIR /SlowFast/ActivityNet/Crawler/Kinetics/k400/train_256 DATA.PATH_PREFIX /SlowFast/ActivityNet/Crawler/Kinetics/k400/train_256 DATA.PATH_LABEL_SEPARATOR , TRAIN.EVAL_PERIOD 1 TRAIN.CHECKPOINT_PERIOD 100 TRAIN.BATCH_SIZE 32 TRAIN.SAVE_LATEST False NUM_GPUS 4 NUM_SHARDS 2 SOLVER.MAX_EPOCH 55 SOLVER.BASE_LR 1e-5 SOLVER.BASE_LR_SCALE_NUM_SHARDS False SOLVER.WARMUP_EPOCHS 5. TEST.NUM_ENSEMBLE_VIEWS 4 TEST.NUM_SPATIAL_CROPS 3 TEST.TEST_BEST True TEST.ADD_SOFTMAX True TEST.BATCH_SIZE 128 RNG_SEED 6666 OUTPUT_DIR /homesda/home/ybjia/UniFormerV2/exp/k400/k400_b16_f8x224

**Comment by Andy1621** [comment]
Can you provide the details of your problem? It's hard to understand now...😂
