### ISSUE TITLE
Evaluation using mit - getting the embeddings

### ISSUE THREAD

**Issue by anjugopinath** [OpenGVLab/UniFormerV2#27]
I am performing evaluation using mit. This is my test.sh file:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/4654298/218172204-6ffb4b55-b7a5-4591-a824-59897d7a9caa.png">

I want to get the output (embeddings) of the second last layer. I will be using pytorch hooks to do this.
Which file will give me the access to the model during evaluation?

**Comment by Andy1621** [comment]
The model code is [here](https://github.com/OpenGVLab/UniFormerV2/blob/main/slowfast/models/uniformerv2_model.py).
