### ISSUE TITLE
请问一下怎么用单gpu进行训练

### ISSUE THREAD

**Issue by hfjwc** [OpenGVLab/UniFormerV2#28]
我训练遇到了这个问题:
![1677034115293](https://user-images.githubusercontent.com/43467289/220508619-da56be2c-7564-49fe-b7bf-6ae8c35ebbd3.jpg)

**Comment by hfjwc** [comment]
我的config.yaml:
TRAIN:
  ENABLE: True
  DATASET: kinetics_sparse
  BATCH_SIZE: 2
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: decord
  NUM_FRAMES: 8
  SAMPLING_RATE: 16
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: '/home/bl/work/source/algorithm_project/mmaction2/data/kinetics400_tiny/videos_data'
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
UNIFORMERV2:
  BACKBONE: 'uniformerv2_b16'
  N_LAYERS: 4
  N_DIM: 768
  N_HEAD: 12
  MLP_FACTOR: 4.0
  BACKBONE_DROP_PATH_RATE: 0.
  DROP_PATH_RATE: 0.
  MLP_DROPOUT: [0.5, 0.5, 0.5, 0.5]
  CLS_DROPOUT: 0.5
  RETURN_LIST: [8, 9, 10, 11]
  NO_LMHRA: True
  TEMPORAL_DOWNSAMPLE: False
AUG:
  NUM_SAMPLE: 1
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 4e-4
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 0.
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 2
  ARCH: uniformerv2
  MODEL_NAME: Uniformerv2
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  USE_CHECKPOINT: False
  CHECKPOINT_NUM: [0]
TEST:
  ENABLE: True
  DATASET: kinetics_sparse
  BATCH_SIZE: 256
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: False
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: './runs'

**Comment by Andy1621** [comment]
see https://github.com/facebookresearch/SlowFast/issues/308
