### ISSUE TITLE
Calculating average of predicted results

### ISSUE THREAD

**Issue by anjugopinath** [OpenGVLab/UniFormerV2#29]
Hi,

I am performing evaluation on 10 images.
I know that the code samples N clips and 3 crops from a single input video.

The below code is from the perform_test() function inside the file test_net.py 

![image](https://user-images.githubusercontent.com/4654298/220766108-f03c6059-4e1b-40e6-97c6-c515f8ef455f.png)

Below are the results of the 2 print statements marked as 1 and 2 in green color respectively:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/4654298/220766351-d1245367-5a5f-4333-968a-fedc9de18341.png">

Why is one of size 28 and the other of size 10?
Where in the code do you perform averaging to calculate the final results?

**Comment by Andy1621** [comment]
Note that the `pred` is the prediction in the current forward. Thus the `pred` size is equal to `batch_size` x `num_clips` x `num_crops`.

However, the `test_meter.video_preds` stores the predictions of the whole test datasets, its length is `num_test_videos`.

The testing is calculated in [utils/meters.py](https://github.com/OpenGVLab/UniFormerV2/blob/0dbc776fd9ba4971db269f24fd4474da349b2aa2/slowfast/utils/meters.py#L297-L330).
