### ISSUE TITLE
Map video_idx in test_net.py to the actual input videos

### ISSUE THREAD

**Issue by anjugopinath** [OpenGVLab/UniFormerV2#30]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/4654298/221003208-5263f089-f417-4d6d-bfc4-2248716bf06e.png">

In the perform_test() function in test_net.py, I want to find which video_idx index is mapped to which video.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/4654298/221003603-17315598-9f68-42fe-adb0-3cedcd7da616.png">

As shown in the above image, there are 32 ids. I also sorted it. I have 10 input videos. How do I find which video_idx is mapped to which of the 10 input videos.

**Comment by Andy1621** [comment]
Why do you want to find which video_idx index is mapped to which video? Maybe you misunderstood the testing logic. I suggest you check the logic in [TestMeter](https://github.com/OpenGVLab/UniFormerV2/blob/0dbc776fd9ba4971db269f24fd4474da349b2aa2/slowfast/utils/meters.py#L231-L404).
