### ISSUE TITLE
How much minimum VRAM is needed to train and inference(loading model)??

### ISSUE THREAD

**Issue by JeonDF** [OpenGVLab/UniFormerV2#31]
Hello.

I trained 'k400_k710_uniformerv2_l14_32x336' model referring to example config file (on this git repo) and Train is finished successfully.

I decreased batch size to avoid **[CUDA out of memory]** problem to 4.
(My device has 4 GPU and Batch size = 4 → 1 batch per 1 GPU in parallel) 

When I trained the model , In batch size from 256 ~ 8, the CUDA out of memory error was occured.

In Batch size = 4, The Training is processed for 7 days, and finally, the output model file( best.pyth ) was generated.

However, when I load the output model for inference, error is occured.

`
RuntimeError: CUDA out of memory. Tried to allocate 184.00 MiB (GPU 0; 23.69 GiB total capacity; 21.57 GiB already allocated; 158.62 MiB free; 21.97 GiB reserved in total by PyTorch)
`

- This is my GPU Spec
  . NVIDIA RTX A5000 x 4 cards  ( 24GB VRAM per 1 GPU )

I want to train **[k400_k710_uniformerv2_l14_32x336]** model and **[k400_k710_uniformerv2_l14_32x224]** model.
Also I want to use them for inference.
  
How much minimum VRAM is needed for train?? 
And How much minimum VRAM is needed for inference??

I would be grateful if you could tell me minimum amount of VRAM.

**Comment by JeonDF** [comment]
In config.yaml, 
----------------------------------------
MODEL:
...
  USE_CHECKPOINT: False
  CHECKPOINT_NUM: [0]
...
----------------------------------------

What do 'USE_CHECKPOINT' and 'CHECKPOINT_NUM' mean?

In example file (~~ /exp/k400/k400+k710_l14_f32x224/config.yaml),
values are as follows :
----------------------------------------
  USE_CHECKPOINT: False
  CHECKPOINT_NUM: [0]
----------------------------------------

And example file (~~ /exp/k400/k400+k710_l14_f32x336/config.yaml), 
(→ this is my train success case without 'CUDA out of memory' problem)
values are as follows :
----------------------------------------
  USE_CHECKPOINT: True
  CHECKPOINT_NUM: [24]
----------------------------------------


As my train success case, I modified the config file of [k400+k710_l14_f32x224] as follows :
----------------------------------------
  USE_CHECKPOINT: True
  CHECKPOINT_NUM: [24]
----------------------------------------

and I run the run.sh file of [k400+k710_l14_f32x224] (run.sh was modified based on my environment.)
CUDA out of memory error doesn't occur.

To train [k400+k710_l14_f32x224] model, Is modifying the value of config.yaml ok to train the model?
----------------------------------------
 USE_CHECKPOINT ⇒ False to True
 CHECKPOINT_NUM ⇒ [0] to [24]
----------------------------------------

**Comment by Andy1621** [comment]
Yes, your change works. `USE_CHECKPOINT` means use [torch.utils.checkpoint](https://pytorch.org/docs/stable/checkpoint.html).

For inference, the `CUDA out of memory` may be due to the following sentence:
https://github.com/OpenGVLab/UniFormerV2/blob/0dbc776fd9ba4971db269f24fd4474da349b2aa2/tools/test_net.py#L165-L166

You can simply comment out the code.

**Comment by JeonDF** [comment]
> Yes, your change works. `USE_CHECKPOINT` means use [torch.utils.checkpoint](https://pytorch.org/docs/stable/checkpoint.html).
> 
> For inference, the `CUDA out of memory` may be due to the following sentence:
> 
> https://github.com/OpenGVLab/UniFormerV2/blob/0dbc776fd9ba4971db269f24fd4474da349b2aa2/tools/test_net.py#L165-L166
> 
> You can simply comment out the code.

No. 
In the train process, test also was finished normally and final log text is following.
(top1_acc : 88.49)

>[INFO] logging.py:  99: json_stats: {"cur_iter": "59304", "eta": "0:00:00", "split": "test_iter", "time_diff": 0.68495}
[INFO] logging.py:  99: json_stats: {"split": "test_final", "top1_acc": "88.49", "top5_acc": "97.98"}

After that, I used the model file (.pyth file), which is the result output file for inference.
And the program occured `CUDA out of memory` error after it inference 1 section consisting of 9 image frames.

Perhaps, It seems that [k400_k710_uniformerv2_l14_32x336] model is needed more than 24GB VRAM for inference.

**Comment by Andy1621** [comment]
You can try to use fewer frames or smaller models 😋

**Comment by JeonDF** [comment]
OK.
I'll have to buy much better GPU 😄

**Comment by JeonDF** [comment]
OK.
I'll have to buy much better GPU 😄

**Comment by Andy1621** [comment]
hhhhh
