### ISSUE TITLE
Inference action score of Trained Model is all 0.01xxx

### ISSUE THREAD

**Issue by JeonDF** [OpenGVLab/UniFormerV2#32]
I trained [k400+k710_l14_f32x224] model based on 

　(1) config.yaml **[UniFormerV2/exp/k400/k400+k710_l14_f32x224/]**
　(2) run.sh **[UniFormerV2/exp/k400/k400+k710_l14_f32x224/]**
　(3) test.csv, train.csv, val.csv **from DeepMind kinetics-400 dataset**
　　(→ test.csv and val.csv is same on your dataset sharing me, so, I used val.csv same as test.csv (almost same as your csv file) )

After training and test is all over, best.pyth file is generated.
I inference some videos through the model I trained, 
but The model inference result top-5 score of recognized action is all 0.01xxx  in all many sections of video file.

I used the model same as I used a model from UniformerV2 model zoo **[k400_k710_uniformerv2_l14_32x224.pyth]**.
I execute same python code **(only path variable of model file is different)**,

What is wrong?
I used a model **[k400_k710_uniformerv2_l14_32x224.pyth]** provided from model zoo of this repo.
and I saw that the model worked well.

Why doesn't the model I trained work? 😢 

When I executed the model I trained firstly, following error message was printed 
and I modified my code to avoid that error.
　→ g_model.load_state_dict(state_dict, **_strict=False_**)  → Is this wrong?

After I add the option (**_strict=False_**), the model I trained doesn't occur error.
However, the result of inference is all 0.01xxx scores.

The way how I trained the model was wrong?

-----

> File "predTest.py", line 451, in <module>
    main(sys.argv)
  File "predTest.py", line 413, in main
    g_model.load_state_dict(state_dict)
  File "/root/anaconda3/envs/UniFormerV2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Uniformerv2:
        Missing key(s) in state_dict: "backbone.class_embedding", "backbone.positional_embedding", "backbone.conv1.weight", "backbone.ln_pre.weight", "backbone.ln_pre.bias", "backbone.transformer.temporal_cls_token", "backbone.transformer.balance", "backbone.transformer.resblocks.0.attn.in_proj_weight", "backbone.transformer.resblocks.0.attn.in_proj_bias", "backbone.transformer.resblocks.0.attn.out_proj.weight", "backbone.transformer.resblocks.0.attn.out_proj.bias", "backbone.transformer.resblocks.0.ln_1.weight", "backbone.transformer.resblocks.0.ln_1.bias", "backbone.transformer.resblocks.0.mlp.c_fc.weight", "backbone.transformer.resblocks.0.mlp.c_fc.bias", "backbone.transformer.resblocks.0.mlp.c_proj.weight", "backbone.transformer.resblocks.0.mlp.c_proj.bias", "backbone.transformer.resblocks.0.ln_2.weight", "backbone.transformer.resblocks.0.ln_2.bias", "backbone.transformer.resblocks.1.attn.in_proj_weight", "backbone.transformer.resblocks.1.attn.in_proj_bias", "backbone.transformer.resblocks.1.attn.out_proj.weight", "backbone.transformer.resblocks.1.attn.out_proj.bias", "backbone.transformer.resblocks.1.ln_1.weight", "backbone.transformer.resblocks.1.ln_1.bias", "backbone.transformer.resblocks.1.mlp.c_fc.weight", "backbone.transformer.resblocks.1.mlp.c_fc.bias", "backbone.transformer.resblocks.1.mlp.c_proj.weight", "backbone.transformer.resblocks.1.mlp.c_proj.bias", "backbone.transformer.resblocks.1.ln_2.weight", "backbone.transformer.resblocks.1.ln_2.bias", "backbone.transformer.resblocks.2.attn.in_proj_weight", "backbone.transformer.resblocks.2.attn.in_proj_bias", "backbone.transformer.resblocks.2.attn.out_proj.weight", "backbone.transformer.resblocks.2.attn.out_proj.bias", "backbone.transformer.resblocks.2.ln_1.weight", "backbone.transformer.resblocks.2.ln_1.bias", "backbone.transformer.resblocks.2.mlp.c_fc.weight", "backbone.transformer.resblocks.2.mlp.c_fc.bias", "backbone.transformer.resblocks.2.mlp.c_proj.weight", "backbone.transformer.resblocks.2.mlp.c_proj.bias", "backbone.transformer.resblocks.2.ln_2.weight", "backbone.transformer.resblocks.2.ln_2.bias", "backbone.transformer.resblocks.3.attn.in_proj_weight", "backbone.transformer.resblocks.3.attn.in_proj_bias", "backbone.transformer.resblocks.3.attn.out_proj.weight", "backbone.transformer.resblocks.3.attn.out_proj.bias", "backbone.transformer.resblocks.3.ln_1.weight", "backbone.transformer.resblocks.3.ln_1.bias", "backbone.transformer.resblocks.3.mlp.c_fc.weight", "backbone.transformer.resblocks.3.mlp.c_fc.bias", "backbone.transformer.resblocks.3.mlp.c_proj.weight", "backbone.transformer.resblocks.3.mlp.c_proj.bias", "backbone.transformer.resblocks.3.ln_2.weight", "backbone.transformer.resblocks.3.ln_2.bias", "backbone.transformer.resblocks.4.attn.in_proj_weight", "backbone.transformer.resblocks.4.attn.in_proj_bias", "backbone.transformer.resblocks.4.attn.out_proj.weight", "backbone.transformer.resblocks.4.attn.out_proj.bias", "backbone.transformer.resblocks.4.ln_1.weight", "backbone.transformer.resblocks.4.ln_1.bias", "backbone.transformer.resblocks.4.mlp.c_fc.weight", "backbone.transformer.resblocks.4.mlp.c_fc.bias", "backbone.transformer.resblocks.4.mlp.c_proj.weight", "backbone.transformer.resblocks.4.mlp.c_proj.bias", "backbone.transformer.resblocks.4.ln_2.weight", "backbone.transformer.resblocks.4.ln_2.bias", "backbone.transformer.resblocks.5.attn.in_proj_weight", "backbone.transformer.resblocks.5.attn.in_proj_bias", "backbone.transformer.resblocks.5.attn.out_proj.weight", "backbone.transformer.resblocks.5.attn.out_proj.bias", "backbone.transformer.resblocks.5.ln_1.weight", "backbone.transformer.resblocks.5.ln_1.bias", "backbone.transformer.resblocks.5.mlp.c_fc.weight", "backbone.transformer.resblocks.5.mlp.c_fc.bias", "backbone.transformer.resblocks.5.mlp.c_proj.weight", "backbone.transformer.resblocks.5.mlp.c_proj.bias", "backbone.transformer.resblocks.5.ln_2.weight", "backbone.transformer.resblocks.5.ln_2.bias", "backbone.transformer.resblocks.6.attn.in_proj_weight", "backbone.transformer.resblocks.6.attn.in_proj_bias", "backbone.transformer.resblocks.6.attn.out_proj.weight", "backbone.transformer.resblocks.6.attn.out_proj.bias", "backbone.transformer.resblocks.6.ln_1.weight", "backbone.transformer.resblocks.6.ln_1.bias", "backbone.transformer.resblocks.6.mlp.c_fc.weight", "backbone.transformer.resblocks.6.mlp.c_fc.bias", "backbone.transformer.resblocks.6.mlp.c_proj.weight", "backbone.transformer.resblocks.6.mlp.c_proj.bias", "backbone.transformer.resblocks.6.ln_2.weight", "backbone.transformer.resblocks.6.ln_2.bias", "backbone.transformer.resblocks.7.attn.in_proj_weight", "backbone.transformer.resblocks.7.attn.in_proj_bias", "backbone.transformer.resblocks.7.attn.out_proj.weight", "backbone.transformer.resblocks.7.attn.out_proj.bias", "backbone.transformer.resblocks.7.ln_1.weight", "backbone.transformer.resblocks.7.ln_1.bias", "backbone.transformer.resblocks.7.mlp.c_fc.weight", "backbone.transformer.resblocks.7.mlp.c_fc.bias", "backbone.transformer.resblocks.7.mlp.c_proj.weight", "backbone.transformer.resblocks.7.mlp.c_proj.bias", "backbone.transformer.resblocks.7.ln_2.weight", "backbone.transformer.resblocks.7.ln_2.bias", 
                                                   ..... 
>"backbone.transformer.resblocks.23.attn.in_proj_weight", "backbone.transformer.resblocks.23.attn.in_proj_bias", "backbone.transformer.resblocks.23.attn.out_proj.weight", "backbone.transformer.resblocks.23.attn.out_proj.bias", "backbone.transformer.resblocks.23.ln_1.weight", "backbone.transformer.resblocks.23.ln_1.bias", "backbone.transformer.resblocks.23.mlp.c_fc.weight", "backbone.transformer.resblocks.23.mlp.c_fc.bias", "backbone.transformer.resblocks.23.mlp.c_proj.weight", "backbone.transformer.resblocks.23.mlp.c_proj.bias", "backbone.transformer.resblocks.23.ln_2.weight", "backbone.transformer.resblocks.23.ln_2.bias", "backbone.transformer.dpe.0.weight", "backbone.transformer.dpe.0.bias", "backbone.transformer.dpe.1.weight", "backbone.transformer.dpe.1.bias", "backbone.transformer.dpe.2.weight", "backbone.transformer.dpe.2.bias", "backbone.transformer.dpe.3.weight", "backbone.transformer.dpe.3.bias", "backbone.transformer.dec.0.attn.in_proj_weight", "backbone.transformer.dec.0.attn.in_proj_bias", "backbone.transformer.dec.0.attn.out_proj.weight", "backbone.transformer.dec.0.attn.out_proj.bias", "backbone.transformer.dec.0.ln_1.weight", "backbone.transformer.dec.0.ln_1.bias", "backbone.transformer.dec.0.mlp.c_fc.weight", "backbone.transformer.dec.0.mlp.c_fc.bias", "backbone.transformer.dec.0.mlp.c_proj.weight", "backbone.transformer.dec.0.mlp.c_proj.bias", "backbone.transformer.dec.0.ln_2.weight", "backbone.transformer.dec.0.ln_2.bias", "backbone.transformer.dec.0.ln_3.weight", "backbone.transformer.dec.0.ln_3.bias", "backbone.transformer.dec.1.attn.in_proj_weight", "backbone.transformer.dec.1.attn.in_proj_bias", "backbone.transformer.dec.1.attn.out_proj.weight", "backbone.transformer.dec.1.attn.out_proj.bias", "backbone.transformer.dec.1.ln_1.weight", "backbone.transformer.dec.1.ln_1.bias", "backbone.transformer.dec.1.mlp.c_fc.weight", "backbone.transformer.dec.1.mlp.c_fc.bias", "backbone.transformer.dec.1.mlp.c_proj.weight", "backbone.transformer.dec.1.mlp.c_proj.bias", "backbone.transformer.dec.1.ln_2.weight", "backbone.transformer.dec.1.ln_2.bias", "backbone.transformer.dec.1.ln_3.weight", "backbone.transformer.dec.1.ln_3.bias", "backbone.transformer.dec.2.attn.in_proj_weight", "backbone.transformer.dec.2.attn.in_proj_bias", "backbone.transformer.dec.2.attn.out_proj.weight", "backbone.transformer.dec.2.attn.out_proj.bias", "backbone.transformer.dec.2.ln_1.weight", "backbone.transformer.dec.2.ln_1.bias", "backbone.transformer.dec.2.mlp.c_fc.weight", "backbone.transformer.dec.2.mlp.c_fc.bias", "backbone.transformer.dec.2.mlp.c_proj.weight", "backbone.transformer.dec.2.mlp.c_proj.bias", "backbone.transformer.dec.2.ln_2.weight", "backbone.transformer.dec.2.ln_2.bias", "backbone.transformer.dec.2.ln_3.weight", "backbone.transformer.dec.2.ln_3.bias", "backbone.transformer.dec.3.attn.in_proj_weight", "backbone.transformer.dec.3.attn.in_proj_bias", "backbone.transformer.dec.3.attn.out_proj.weight", "backbone.transformer.dec.3.attn.out_proj.bias", "backbone.transformer.dec.3.ln_1.weight", "backbone.transformer.dec.3.ln_1.bias", "backbone.transformer.dec.3.mlp.c_fc.weight", "backbone.transformer.dec.3.mlp.c_fc.bias", "backbone.transformer.dec.3.mlp.c_proj.weight", "backbone.transformer.dec.3.mlp.c_proj.bias", "backbone.transformer.dec.3.ln_2.weight", "backbone.transformer.dec.3.ln_2.bias", "backbone.transformer.dec.3.ln_3.weight", "backbone.transformer.dec.3.ln_3.bias", "backbone.transformer.proj.0.weight", "backbone.transformer.proj.0.bias", "backbone.transformer.proj.2.weight", "backbone.transformer.proj.2.bias".
        Unexpected key(s) in state_dict: "epoch", "model_state", "optimizer_state", "scaler", "cfg".

**Comment by JeonDF** [comment]
I think that train is finished normally.
Actually, the final 2 lines of log was printed as following and the top-1 accuracy was recorded 88.18 

[INFO] logging.py:  99: json_stats: {"cur_iter": "59304", "eta": "0:00:00", "split": "test_iter", "time_diff": 0.28015}
[INFO] logging.py:  99: json_stats: {"split": "test_final", "top1_acc": "88.18", "top5_acc": "97.85"}

**Comment by Andy1621** [comment]
It seems that you do not load the model properly. 
In your model files, there are keys: "epoch", "model_state", "optimizer_state", "scaler", "cfg".
It seems that you should save the "model_state" as the final model file.

**Comment by JeonDF** [comment]
As you said, when I save  the "model_state", the model I trained work well.
Thanks for your answer :)

**Comment by sulizhi** [comment]
May I know how to save?
