### ISSUE TITLE
模型初始化问题

### ISSUE THREAD

**Issue by zhanghang-official** [OpenGVLab/UniFormerV2#33]
感谢您的工作！我这边想用clip-vit权重进行模型参数初始化，想请教下初始化代码的逻辑，我自己看不是很清楚，十分感谢！（finetune参数是工程需要自己加入的）

![image](https://user-images.githubusercontent.com/121210699/223017828-8882901b-166a-4233-9442-641327948bfb.png)

**Comment by zhanghang-official** [comment]
`def load_state_dict(model, state_dict, finetune, delete_special_hard=False):
    if not finetune:
        state_dict_3d = model.state_dict()
        for k in state_dict.keys():
            if state_dict[k].shape != state_dict_3d[k].shape:
                if len(state_dict_3d[k].shape) <= 2:
                    continue
                time_dim = state_dict_3d[k].shape[2]
                state_dict[k] = inflate_weight(state_dict[k], time_dim)
        model.load_state_dict(state_dict, strict=False)
    else:
        if delete_special_hard:
            del state_dict['transformer.proj.2.weight']
            del state_dict['transformer.proj.2.bias']
        model.load_state_dict(state_dict, strict=False)

    return model`

**Comment by zhanghang-official** [comment]
![image](https://user-images.githubusercontent.com/121210699/223017755-b057c619-3ea2-410b-80b1-dc9c51267b24.png)

**Comment by Andy1621** [comment]
对于初始化，主要需要注意的是对时空三维卷积的初始化。对于图像预训练的模型，由于使用的是空间二维卷积，需要在时间尺度上进行平均或者填零，具体可以看infalte_weight函数。

**Comment by zhanghang-official** [comment]
明白啦，感谢！
