### ISSUE TITLE
wether the pre-training dataset K710 is available ?

### ISSUE THREAD

**Issue by peiliu0408** [OpenGVLab/UniFormerV2#36]
just as paper presented, the pre-training on K710, i.e., the combination of K400, 600, 700,  results shorter training cost on downstreaming task, I wonder whether this annotation file is available?

**Comment by Andy1621** [comment]
Hi! Please Check [DATASET.md](https://github.com/OpenGVLab/UniFormerV2/blob/main/DATASET.md). The annotation file can found [here](https://drive.google.com/drive/folders/17cJd2qopv-pEG8NSghPFjZo1UUZ6NLVm).
