### ISSUE TITLE
how to video  transform. torch_imgs  input

### ISSUE THREAD

**Issue by weichengzhili** [OpenGVLab/UniFormerV2#37]
我想用  k400_k710_uniformerv2_l14_32x336.pyth 模型来识别视频  我怎么把给定的视频转化成  32x3x2 格式的Frame  向量数据 有通用方法吗  输入指定的 转换格式比如  2x3x2 格式的Frame  输出转换好后的Tensor向量数据

**Comment by Andy1621** [comment]
可以参考huggingface上面的demo
https://huggingface.co/spaces/Andy1621/uniformerv2_demo/blob/2e234084fa2779baac8c0e7fb567de4041b20154/app.py#L57-L81

**Comment by weichengzhili** [comment]
我测试的是 k400_k710_uniformerv2_l14_32x336.pyth 模型  启动采用了 uniformerv2_l14_336 这个方法  
调整两处参数 ：
第一处, get_index方法里面的 num_segments修改成32 
第二处 , uniformerv2_l14_336  t_size 修改成32
结果报了错误： The size of tensor a (257) must match the size of tensor b (577) at non-singleton dimension 1 请问一下是不是需要调整其他参数 或者视频转换Frame 方法要重写

**Comment by Andy1621** [comment]
抱歉回复晚了，这应该是因为机器内存不够，程序kill掉了，你可以尝试更小的模型，大部分情况下预测比较相近的~~

**Comment by weichengzhili** [comment]
这个有内存阈值吗 多大合适

**Comment by Andy1621** [comment]
没有确定的，不是336分辨率的应该可以跑
