### ISSUE TITLE
测试预训练模型 k400_k710_uniformerv2_l14_32x336.pyth 程序自动退出

### ISSUE THREAD

**Issue by weichengzhili** [OpenGVLab/UniFormerV2#38]
我在 mac 上跑 k400_k710_uniformerv2_l14_32x336.pyth  模型 mac arm版本 16g内存 程序直接闪崩 是不是需要什么硬件条件

**Comment by Andy1621** [comment]
mac arm不太好跑哈哈，你可以尝试更小的模型，结果差不多的~

**Comment by weichengzhili** [comment]
小模型的 k400 和 k600 没问题

**Comment by Andy1621** [comment]
可以的
