### ISSUE TITLE
在 demo 中  kinetics_class_index.py 中 序列号是按照什么规则来排序的 我测试k600 的 这个py中 kinetics_classnames序列怎么排

### ISSUE THREAD

**Issue by weichengzhili** [OpenGVLab/UniFormerV2#40]

**Comment by Andy1621** [comment]
请参考[DATA](https://github.com/OpenGVLab/UniFormerV2/blob/main/DATASET.md)，每个数据集都提供了class序列的，见[drive](https://drive.google.com/drive/folders/17VB-XdF3Kfr9ORmnGyXCxTMs86n0L4QL)。

**Comment by weichengzhili** [comment]
已解决 谢谢
