### ISSUE TITLE
如何屏蔽不同平台训练模型的差异性

### ISSUE THREAD

**Issue by weichengzhili** [OpenGVLab/UniFormerV2#41]
我用 mac arm 跑出来的结果 和 linux centos 平台跑出来的结果不一样 差别比较大 是不是可以设置什么参数来屏蔽掉不同平台的差别

**Comment by Andy1621** [comment]
具体是什么结果不一样呢？能否提供更多细节

**Comment by weichengzhili** [comment]
我用 k600_k710_uniformerv2_l14_32x224.pyth 模型来验证视频识别结果 mac arm 上跑的结果和 centos7 上跑的结果不一样

**Comment by Andy1621** [comment]
是概率不一样，还是类别也不一样
