### ISSUE TITLE
The problem with loading and saving the model

### ISSUE THREAD

**Issue by sulizhi** [OpenGVLab/UniFormerV2#44]
It seems that you do not load the model properly. 
In your model files, there are keys: "epoch", "model_state", "optimizer_state", "scaler", "cfg".
It seems that you should save the "model_state" as the final model file.

_Originally posted by @Andy1621 in https://github.com/OpenGVLab/UniFormerV2/issues/32#issuecomment-1447845837_

**Comment by sulizhi** [comment]
I met the same question as he met. Can I know how to load and save model correctly? Thanks very much! Looking forward to your reply!

**Comment by Andy1621** [comment]
Please check the `utils/checkpoint.py` to see the logic of loading and saving model, like https://github.com/OpenGVLab/UniFormerV2/blob/cab2a5c3ec7b6e036ec78021b9f64b1221da5ba0/slowfast/utils/checkpoint.py#L118-L149
