### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by xiezexun** [OpenGVLab/UniFormerV2#49]
作者您好，请问vit的预训练模型在哪里下载？
_MODELS = {
"ViT-B/16": os.path.join(MODEL_PATH, "ViT-B-16.pth"),
"ViT-L/14": os.path.join(MODEL_PATH, "vit_l14.pth"),
"ViT-L/14_336": os.path.join(MODEL_PATH, "vit_l14_336.pth"),
}

**Comment by Andy1621** [comment]
请参考https://github.com/OpenGVLab/UniFormerV2/blob/main/INSTRUCTIONS.md#training

**Comment by xiezexun** [comment]
不好意思作者，打扰您了，看了您上面的链接，请问是用的open_clip中的预训练模型吗？地址是：https://github.com/mlfoundations/open_clip/releases/tag/v0.2-weights

**Comment by Andy1621** [comment]
用的是openai的clip模型https://github.com/openai/CLIP

**Comment by xiezexun** [comment]
好的，感谢您的回复，我已经知道了

**Comment by ZachWong123** [comment]
您好 请问您方便把您提取出的vit预训练权重分享一下么 我这边由于环境问题 没办法进行CLIP库的安装 非常感谢
