### ISSUE TITLE
关于代码复现，在somethingv2数据集上训练的相关问题

### ISSUE THREAD

**Issue by xiezexun** [OpenGVLab/UniFormerV2#50]
作者您好，给予您的代码我在somethingv2数据集上进行了复现，配置文件采用的是“exp/sthv2/ssv2_l14_f16x224/config.yaml”，我修改了dataset名称、batch_size大小和数据集的路径，看到您之前在问答过程中说过 “如果您使用视频来训练 sthsthv2，则可以简单地重用kinetics_sparse.py.” 因此我将dataset名字改为了kinetics400，但很意外的是我在训练开始的时候，loss很大，且在4~6之间波动，然后top1_err\top5_err均为100%，我用的是单GPU4090，希望您能帮我看一下问题出在哪里，我觉得是不正常的。配置文件内容如下：

TRAIN:
  ENABLE: True
  DATASET: kinetics_sparse
  BATCH_SIZE: 2
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 16
  RANDOM_FLIP: False
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  # PATH_TO_DATA_DIR: path-to-imagenet-dir
  PATH_PREFIX: ../../data/somethingV2/something-something-v2
  PATH_TO_DATA_DIR: ../../data/somethingV2/annotations
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
UNIFORMERV2:
  BACKBONE: 'uniformerv2_l14'
  N_LAYERS: 16
  N_DIM: 1024
  N_HEAD: 16
  MLP_FACTOR: 4.0
  BACKBONE_DROP_PATH_RATE: 0.2
  DROP_PATH_RATE: 0.4
  MLP_DROPOUT: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  CLS_DROPOUT: 0.5
  RETURN_LIST: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
  DW_REDUCTION: 1.5
  NO_LMHRA: False
  DOUBLE_LMHRA: True
  TEMPORAL_DOWNSAMPLE: True
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 4e-4
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 0.
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 174
  ARCH: uniformerv2
  MODEL_NAME: Uniformerv2
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  USE_CHECKPOINT: True
  CHECKPOINT_NUM: [15]
TEST:
  ENABLE: True
  DATASET: sth
  BATCH_SIZE: 256
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: False
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

**Comment by Andy1621** [comment]
sth数据集的话，我应该上传过专门的[sth.py](https://github.com/OpenGVLab/UniFormerV2/blob/main/slowfast/datasets/sth.py)。对于训练，我上传过[训练log](https://drive.google.com/file/d/1BQG2tfCYALWfFWflSRYcofNqAWPAwqjU/view?usp=drive_link)，您可以大概对照看看
