### ISSUE TITLE
Finetuning with our data.

### ISSUE THREAD

**Issue by Ravindu-Yasas-Nagasinghe** [OpenGVLab/UniFormerV2#51]
I want to finetune this model to the dataset CrossTask. 
'''
wget https://www.di.ens.fr/~dzhukov/crosstask/crosstask_release.zip

wget https://www.di.ens.fr/~dzhukov/crosstask/crosstask_features.zip

wget https://vision.eecs.yorku.ca/WebShare/CrossTask_s3d.zip

unzip '*.zip'
'''

Can you please guide me through the process of doing this.
Thank you

**Comment by Andy1621** [comment]
You can prepare the same annotation files as [here](https://drive.google.com/drive/folders/17VB-XdF3Kfr9ORmnGyXCxTMs86n0L4QL), and then simply use the same training scripts.
