### ISSUE TITLE
关于datasets文件夹下loader.py中构建dataloader的问题

### ISSUE THREAD

**Issue by YJforgithub** [OpenGVLab/UniFormerV2#54]
![image](https://github.com/OpenGVLab/UniFormerV2/assets/66665777/949f70ce-8e31-44ae-b713-aa1f657fb945)
![image](https://github.com/OpenGVLab/UniFormerV2/assets/66665777/3cd5b80e-86fb-415d-8e67-77df04e516ba)
![image](https://github.com/OpenGVLab/UniFormerV2/assets/66665777/bc4e9607-f0f4-4ac6-9438-3a6b7d98925f)
![image](https://github.com/OpenGVLab/UniFormerV2/assets/66665777/f6053939-eae8-4dd0-a210-d804968712a9)
我采用的config.yaml为K400_b16_f8x224，dataset为torch.utils.data.Dataset，所以line114为false跳到125，但127中的cfg.MULTIGRID._CYCLE为false, config.yaml没有这个参数，defaults.py中有这个参数，为False, 跳到line147执行utils.create_sample(dataset, shuffule, cfg)
![image](https://github.com/OpenGVLab/UniFormerV2/assets/66665777/0cd54739-1745-4c86-831b-906242305354)
但是当我指定一张卡时，会报错，多卡时没问题
![image](https://github.com/OpenGVLab/UniFormerV2/assets/66665777/02b5cc82-1967-4721-8164-b445bd27537d)

能否解释一下这三个判断的作用有啥区别，另外这个错误应该怎么处理，感谢！

**Comment by YJforgithub** [comment]
错误已解决，但是没搞懂dataloader的选择，另外MULTIGRID下的参数起到什么作用，感谢解答！

**Comment by Andy1621** [comment]
MULTIGRID的作用可以查看SlowFast原[codebase](https://github.com/facebookresearch/SlowFast)

**Comment by hahapt** [comment]
> 错误已解决，但是没搞懂dataloader的选择，另外MULTIGRID下的参数起到什么作用，感谢解答！

请问一张卡报错是怎么解决的？
