### ISSUE TITLE
关于K400数据读取

### ISSUE THREAD

**Issue by Elijah-Yi** [OpenGVLab/UniFormerV2#55]
您好：
我在复现的过程中遇到几个问题，希望您有时间解答一下：
1）配置文件中出现重复的参数，在读取的时候会报错，这个已经删除了
![image](https://github.com/OpenGVLab/UniFormerV2/assets/22116117/902e186a-396e-40ad-a43a-297cefcbcdc3)
2）数据读取的时候，出现路径错误第一次修改：
![image](https://github.com/OpenGVLab/UniFormerV2/assets/22116117/63d6e5ac-5347-43e8-a33b-576193c4f808)
修改以后还是出错，发现数据命名规则和csv文档中不一致，我下载到的数据集命名规则如图所示。
![image](https://github.com/OpenGVLab/UniFormerV2/assets/22116117/ac42247d-7038-40ce-9c5f-1f0e230facac)
在数据读取的时候，给的csv 文档中
![image](https://github.com/OpenGVLab/UniFormerV2/assets/22116117/3c34ee98-b9d3-4b75-8279-b751b3613acb)
并没有相应的数字部分。是数据集更换命名规则了吗？还是需要特殊处理？

**Comment by Andy1621** [comment]
我不确定您是否下载了正确的数据集，如果不是从我提供的百度网盘下的话，文件命名可能不同:
链接: https://pan.baidu.com/s/1XNxOlCIyej26iF-RStfLPA  密码: fg5a

**Comment by Elijah-Yi** [comment]
谢谢，已经重新下载了，我看了一下我下载的数据  我的应该是原始数据，您这边给的数据原始已经放缩后的

**Comment by LHX0303** [comment]
您好，我按照您上面给出的网盘地址下载数据集，然后在我的windows上运行`cat xa* >> train_k400.zip`这条命令，文件合并之后解压缩，显示“压缩格式未知或者文件已损坏”。这是什么原因呢，还是说我在下载的过程中出了问题，需要重新下载数据集呢？还有一个问题就是，我这个zip压缩包的文件大小是否正常，因为几个文件合并之后的大小比文件大小的总和要大了50G。
![image](https://github.com/OpenGVLab/UniFormerV2/assets/58901186/4c069388-da2f-420a-8f7b-6959e8ddebdb)

**Comment by Andy1621** [comment]
不确定您问题的具体原因，您也可以下载open datalab的版本，https://opendatalab.com/OpenMMLab/Kinetics-400

确保一下label标签一致

**Comment by LHX0303** [comment]
感谢提点。是因为我之前的数据集在传输的过程中出错了，尝试第3次的时候，可以正常解压了。麻烦了!
