### ISSUE TITLE
关于输入X的维度问题

### ISSUE THREAD

**Issue by perfectFeng** [OpenGVLab/UniFormerV2#56]
您好，我有注意到在计算attention之前，输入X的维度为（H*W, B*T, C），这相当于在不同的batch和T上计算attention，为什么要这么设置呢
![1701327387547](https://github.com/OpenGVLab/UniFormerV2/assets/30884091/6458b768-e180-43cc-a550-2ec1bb1bc0d8)

**Comment by Andy1621** [comment]
因为使用的是CLIP的预训练，主干分支是用的是spatial attention，每帧单独操作
