### ISSUE TITLE
为什么第一个模块的命名为Local_MHRA或者说是Local MHRA Temporal,代码不是的Depthwise 3D Convolution吗？

### ISSUE THREAD

**Issue by zxin4506** [OpenGVLab/UniFormerV2#57]
为什么第一个模块的命名为Local_MHRA或者说是Local MHRA Temporal,代码不是的Depthwise 3D Convolution吗？我的理解MHRA是MultiHeadResidualAttention的意思

**Comment by Andy1621** [comment]
MHRA的可以参考[UniFormerV1](https://github.com/Sense-X/UniFormer)，V2中沿用了V1的概念，Multi-Head Relation Aggregator
