### ISSUE TITLE
Uniformer-v2的网络配置

### ISSUE THREAD

**Issue by mcao92** [OpenGVLab/UniFormerV2#59]
您好，uniformer v2-L 和 uniformer v2-B中 local UniBlock 和 global UniBlock 数量是怎么配置的？文章中没有找到！

**Comment by Andy1621** [comment]
对Kinetics和SSV2数据集设置不同，对Kinetics数据只有global block，对SSV2包含local和glbal。
<img width="464" alt="image" src="https://github.com/OpenGVLab/UniFormerV2/assets/24236723/9755cf1e-8e53-4e00-a844-0989c6acf5b6">

对于Kinetics的Base和Large，global的数量都为后4层。对于SSV2，Base的global数量为后8 (=12x2/3)层，Large的global数量为后16 (=24x2/3)层，所有层都添加local。
<img width="224" alt="image" src="https://github.com/OpenGVLab/UniFormerV2/assets/24236723/deb33c59-9a56-4473-8e41-f46dbcc442a3">


具体设置可以查看[实验目录](https://github.com/OpenGVLab/UniFormerV2/tree/main/exp)。
