### ISSUE TITLE
ONE POTENTIAL BUG

### ISSUE THREAD

**Issue by woodenspirits** [OpenGVLab/UniFormerV2#6]
the following thoughts are based on my guess that you want to calculate the accuracy for top-1 to top-k separately, plz correct me if i mistook your intention.

the original code at slowfast/utils/metrics.py line 39 : "topks_correct = [top_max_k_correct[:k, :].float().sum() for k in ks]"
may result in that , for k=(2，3，....,, k), the summation of the top-k correct values includes the values from top-1 to top-k.
the modified code: "topks_correct = [top_max_k_correct[k-1:k, :].float().sum() for k in ks]"

Thanks!

**Comment by Andy1621** [comment]
Actually, most of the code is directly forked from PySlowFast, so there may NOT be a BUG.
The above code is [here](https://github.com/facebookresearch/SlowFast/blob/main/slowfast/utils/metrics.py).

As for your question, you should know what `top_max_k_correct` means. 
https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/slowfast/utils/metrics.py#L28-L37
The above code will calculate the index where the prediction equals the label. **And there is only one `True` in each row. So in the matrix `top_max_k_correct`, if `True` in the first k columns, the prediction will be right.** 
For example,
```python
top_max_k_correct = [
  [True, False, False, False, False, False, False, False, False, False],  # prediction_1 is right
  [False, False, True, False, False, False, False, False, False, False],  # prediction_3 is right
  [False, False, False, True, False, False, False, False, False, False],  # prediction_4 is right
  [False, False, False, False, False, False, False, False, True, False],  # prediction_9 is right
]
```
The top-1 will be 1/4=0.25. The top-5 will be 3/4=0.75.

**Comment by woodenspirits** [comment]
Thanks for your responding! 
i got it!
