### ISSUE TITLE
找不到somesomev2_rgb_train_split.txt'

### ISSUE THREAD

**Issue by RUSO225** [OpenGVLab/UniFormerV2#61]
如题我在路径中创建了data_list文件夹并将上述文件放到文件夹内但仍然报错FileNotFoundError: [Errno 2] No such file or directory: 'D:/UniFormerV2-main/UniFormerV2-main/data_list/somethingV2/somesomev2_rgb_train_split.txt'这个文件是应该自己生成的吗？还是放进去就好呢？

**Comment by Andy1621** [comment]
您好，请在[这里](https://drive.google.com/drive/folders/186CXXSe54kcAq5rl0ftG37fhg0nsOZzo)下载对应的文件。根据你的报错，你应该创建somethingV2目录中
