### ISSUE TITLE
能否利用本模型完成其他的下游任务？

### ISSUE THREAD

**Issue by MortironX** [OpenGVLab/UniFormerV2#69]
你好，我想请问一下。现在我有一定的数据集（图片和视频）能否把我拥有的数据集喂给模型然后完成一定的识别任务，类似一个输入视频，输出文本的任务？

**Comment by Andy1621** [comment]
可以的，不过本模型是行为识别模型，要用预训练的话，需要用比如K400的动作标签

**Comment by MortironX** [comment]
你好，我想完成一个手语识别，因此从博客中看到你们的代码，我有手语动作的视频和图片以及标签，想请问下，如果使用你们的模型你预估是否能达到预期的目标，完成手语识别。

**Comment by Andy1621** [comment]
可以基于本模型微调，或者基于我们更强的模型[UMT](https://github.com/OpenGVLab/unmasked_teacher)微调

**Comment by MortironX** [comment]
好的，我进一步了解一下，感谢！

**Comment by MortironX** [comment]
你好，我想请教一下，我根据我的手语识别任务，选择使用UMT的微调，目前需要修改data.py里数据路径，下面的cc3m模型，只需要下载umt-b 25m的一个模型就好了？最后想问一下该项目大约需要多大显存，感谢答复

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Andy1621** [comment]
可以自己跑一下看看显存需求哈，直接用umt-b 25m预训练就好

**Comment by MortironX** [comment]
好的，感谢

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by snowkueen** [comment]
您好，请问您微调用到多少数据量
