### ISSUE TITLE
feature extraction

### ISSUE THREAD

**Issue by M-Mokari** [OpenGVLab/UniFormerV2#7]
I want to use your method as extracted feature such as I3D for my special application. could you help me? Do you have extracted feature specially on activity net dataset?

**Comment by Andy1621** [comment]
Sorry. I do not have extracted feature. I am conducting model transfer in Hugging Face and MMAction2, which will provide a feature extractor.

BTW, if you want to extract the feature by yourself, you can use the model code [here](https://huggingface.co/spaces/Andy1621/uniformerv2_demo/blob/main/uniformerv2.py).
Then, you can simply use [the pretrained model I have provided](https://github.com/OpenGVLab/UniFormerV2/blob/main/MODEL_ZOO.md), and merge the model in your progress for feature extraction, like [MMAction2](https://github.com/open-mmlab/mmaction2/blob/master/docs/feature_extraction.md).
You may need to set the sampling rate, and input resolution by yourself.

**Comment by M-Mokari** [comment]
Thanks a lot. It could be useful.

**Comment by liuhaiyang2018** [comment]
I want to use your method as extracted feature too！ could you help me? Modify the model to look like swin transformer or like MMAction2 backbone
