### ISSUE TITLE
加载clip的预训练模型

### ISSUE THREAD

**Issue by xwg0508** [OpenGVLab/UniFormerV2#71]
请问在运行extract.ipynb文件时出现以下错误需要怎么解决呢
<img width="697" alt="328742695-199aed59-0d4a-4409-90c0-c5e61fb411e8" src="https://github.com/OpenGVLab/UniFormerV2/assets/130576216/dc574f98-778c-4ea0-976e-f4dceaf8216d">

conda环境中clip已经安装了
<img width="548" alt="328743075-9ebad3fe-d11c-416b-956c-7336883afc52" src="https://github.com/OpenGVLab/UniFormerV2/assets/130576216/a2e0ef9b-942f-45e1-bce3-b15bb05b844b">

**Comment by Andy1621** [comment]
可以直接使用[源码](https://github.com/openai/CLIP/blob/HEAD/clip/model.py)
