### ISSUE TITLE
您好 关于在自己的数据集上进行训练

### ISSUE THREAD

**Issue by ZachWong123** [OpenGVLab/UniFormerV2#72]
由于我的数据集中的动作有和k400重合的部分 所以我保留了k400原本的映射关系 并且加入了我新加的50种动作的的映射关系 按照这个格式生成了新的.csv文件
![123](https://github.com/OpenGVLab/UniFormerV2/assets/152131842/043acc2e-8a50-4105-a740-f7d6a84228e8)
于是我将config.yaml中的num_classes设置为451 并且将数据集路径改为我的视频和.csv文件存放的路径
但是在我启动任务的时候 会卡在
![123123](https://github.com/OpenGVLab/UniFormerV2/assets/152131842/34d368b5-0850-4908-bc68-7939140c291d)
start epoch这一步 我debug代码 发现代码运行到这一行 好像就进入循环了 
![123132](https://github.com/OpenGVLab/UniFormerV2/assets/152131842/098b8413-a4e5-407d-8255-f9e10e3b70c7)
我不知道现在要如何解决这个问题 恳切希望可以得到您的答复

**Comment by Andy1621** [comment]
可以到dataset的`__getitem__`打印看看

**Comment by ZachWong123** [comment]
非常感谢您的提示 我使用少量视频对比发现 在k400上跑的时候 运行到
![Q%G`Q6M$O_@Z3OOHI KF5F0](https://github.com/OpenGVLab/UniFormerV2/assets/152131842/1215b403-4b39-435b-b55c-b3735d24c708)
_getitem_可以正确print读取到的视频 但是使用我自己构建的数据 这边没有办法print出来

**Comment by ZachWong123** [comment]
![IMG_0684](https://github.com/OpenGVLab/UniFormerV2/assets/152131842/9a29a1c7-2ddd-463a-b171-69af8973df7e)
可以正确获取到我自己构建数据的路径以及labels

**Comment by ZachWong123** [comment]
![L$PRZ~Z)__{X8)C_Z%J)5G](https://github.com/OpenGVLab/UniFormerV2/assets/152131842/d9deef67-898d-4bdf-aa65-61582f4278c8)
并且不跑train 单纯使用我构建的数据 跑测试 也能正确调用_getitem_

**Comment by ZachWong123** [comment]
问题已经解决 非常感谢您的回复
