### ISSUE TITLE
feature extraction

### ISSUE THREAD

**Issue by liuhaiyang2018** [OpenGVLab/UniFormerV2#8]
I want to use your method as extracted feature too！  could you help me?  Modify the model to look like swin transformer or like MMAction2 backbone and cls head？

**Comment by Andy1621** [comment]
Either is OK! It just depends on you. You may need to change the keys of `state_dict` if you modify the model.

You can follow https://github.com/OpenGVLab/UniFormerV2/issues/7. Just do it. Don't hesitate to ask me if you meet any problem.

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
