### ISSUE TITLE
 Where to find the same vit model for loading backbone pretrained weights

### ISSUE THREAD

**Issue by lifengfa** [OpenGVLab/UniFormerV2#9]
The weights I found and the training weights are as follows,：
`odict_keys(['positional_embedding', 'text_projection', 'logit_scale', 'input_resolution', 'context_length', 'vocab_size', 'visual.class_embedding', 'visual.positional_embedding', 'visual.proj', 'visual.conv1.weight', 'visual.ln_pre.weight', 'visual.ln_pre.bias', 'visual.transformer.resblocks.0.attn.in_proj_weight', 'visual.transformer.resblocks.0.attn.in_proj_bias', 'visual.transformer.resblocks.0.attn.out_proj.weight', 'visual.transformer.resblocks.0.attn.out_proj.bias', 'visual.transformer.resblocks.0.ln_1.weight', 'visual.transformer.resblocks.0.ln_1.bias', 'visual.transformer.resblocks.0.mlp.c_fc.weight', 'visual.transformer.resblocks.0.mlp.c_fc.bias', 'visual.transformer.resblocks.0.mlp.c_proj.weight', 'visual.transformer.resblocks.0.mlp.c_proj.bias', 'visual.transformer.resblocks.0.ln_2.weight', 'visual.transformer.resblocks.0.ln_2.bias', 'visual.transformer.resblocks.1.attn.in_proj_weight', 'visual.transformer.resblocks.1.attn.in_proj_bias', 'visual.transformer.resblocks.1.attn.out_proj.weight', 'visual.transformer.resblocks.1.attn.out_proj.bias', 'visual.transformer.resblocks.1.ln_1.weight', 'visual.transformer.resblocks.1.ln_1.bias', 'visual.transformer.resblocks.1.mlp.c_fc.weight', 'visual.transformer.resblocks.1.mlp.c_fc.bias', 'visual.transformer.resblocks.1.mlp.c_proj.weight', 'visual.transformer.resblocks.1.mlp.c_proj.bias', 'visual.transformer.resblocks.1.ln_2.weight', 'visual.transformer.resblocks.1.ln_2.bias', 'visual.transformer.resblocks.2.attn.in_proj_weight', 'visual.transformer.resblocks.2.attn.in_proj_bias', 'visual.transformer.resblocks.2.attn.out_proj.weight', 'visual.transformer.resblocks.2.attn.out_proj.bias', 'visual.transformer.resblocks.2.ln_1.weight', 'visual.transformer.resblocks.2.ln_1.bias', 'visual.transformer.resblocks.2.mlp.c_fc.weight', 'visual.transformer.resblocks.2.mlp.c_fc.bias', 'visual.transformer.resblocks.2.mlp.c_proj.weight', 'visual.transformer.resblocks.2.mlp.c_proj.bias', 'visual.transformer.resblocks.2.ln_2.weight', 'visual.transformer.resblocks.2.ln_2.bias', 'visual.transformer.resblocks.3.attn.in_proj_weight', 'visual.transformer.resblocks.3.attn.in_proj_bias', 'visual.transformer.resblocks.3.attn.out_proj.weight', 'visual.transformer.resblocks.3.attn.out_proj.bias', 'visual.transformer.resblocks.3.ln_1.weight', 'visual.transformer.resblocks.3.ln_1.bias', 'visual.transformer.resblocks.3.mlp.c_fc.weight', 'visual.transformer.resblocks.3.mlp.c_fc.bias', 'visual.transformer.resblocks.3.mlp.c_proj.weight', 'visual.transformer.resblocks.3.mlp.c_proj.bias', 'visual.transformer.resblocks.3.ln_2.weight', 'visual.transformer.resblocks.3.ln_2.bias', 'visual.transformer.resblocks.4.attn.in_proj_weight', 'visual.transformer.resblocks.4.attn.in_proj_bias', 'visual.transformer.resblocks.4.attn.out_proj.weight', 'visual.transformer.resblocks.4.attn.out_proj.bias', 'visual.transformer.resblocks.4.ln_1.weight', 'visual.transformer.resblocks.4.ln_1.bias', 'visual.transformer.resblocks.4.mlp.c_fc.weight', 'visual.transformer.resblocks.4.mlp.c_fc.bias', 'visual.transformer.resblocks.4.mlp.c_proj.weight', 'visual.transformer.resblocks.4.mlp.c_proj.bias', 'visual.transformer.resblocks.4.ln_2.weight', 'visual.transformer.resblocks.4.ln_2.bias', 'visual.transformer.resblocks.5.attn.in_proj_weight', 'visual.transformer.resblocks.5.attn.in_proj_bias', 'visual.transformer.resblocks.5.attn.out_proj.weight', 'visual.transformer.resblocks.5.attn.out_proj.bias', 'visual.transformer.resblocks.5.ln_1.weight', 'visual.transformer.resblocks.5.ln_1.bias', 'visual.transformer.resblocks.5.mlp.c_fc.weight', 'visual.transformer.resblocks.5.mlp.c_fc.bias', 'visual.transformer.resblocks.5.mlp.c_proj.weight', 'visual.transformer.resblocks.5.mlp.c_proj.bias', 'visual.transformer.resblocks.5.ln_2.weight', 'visual.transformer.resblocks.5.ln_2.bias', 'visual.transformer.resblocks.6.attn.in_proj_weight', 'visual.transformer.resblocks.6.attn.in_proj_bias', 'visual.transformer.resblocks.6.attn.out_proj.weight', 'visual.transformer.resblocks.6.attn.out_proj.bias', 'visual.transformer.resblocks.6.ln_1.weight', 'visual.transformer.resblocks.6.ln_1.bias', 'visual.transformer.resblocks.6.mlp.c_fc.weight', 'visual.transformer.resblocks.6.mlp.c_fc.bias', 'visual.transformer.resblocks.6.mlp.c_proj.weight', 'visual.transformer.resblocks.6.mlp.c_proj.bias', 'visual.transformer.resblocks.6.ln_2.weight', 'visual.transformer.resblocks.6.ln_2.bias', 'visual.transformer.resblocks.7.attn.in_proj_weight', 'visual.transformer.resblocks.7.attn.in_proj_bias', 'visual.transformer.resblocks.7.attn.out_proj.weight', 'visual.transformer.resblocks.7.attn.out_proj.bias', 'visual.transformer.resblocks.7.ln_1.weight', 'visual.transformer.resblocks.7.ln_1.bias', 'visual.transformer.resblocks.7.mlp.c_fc.weight', 'visual.transformer.resblocks.7.mlp.c_fc.bias', 'visual.transformer.resblocks.7.mlp.c_proj.weight', 'visual.transformer.resblocks.7.mlp.c_proj.bias', 'visual.transformer.resblocks.7.ln_2.weight', 'visual.transformer.resblocks.7.ln_2.bias', 'visual.transformer.resblocks.8.attn.in_proj_weight', 'visual.transformer.resblocks.8.attn.in_proj_bias', 'visual.transformer.resblocks.8.attn.out_proj.weight', 'visual.transformer.resblocks.8.attn.out_proj.bias', 'visual.transformer.resblocks.8.ln_1.weight', 'visual.transformer.resblocks.8.ln_1.bias', 'visual.transformer.resblocks.8.mlp.c_fc.weight', 'visual.transformer.resblocks.8.mlp.c_fc.bias', 'visual.transformer.resblocks.8.mlp.c_proj.weight', 'visual.transformer.resblocks.8.mlp.c_proj.bias', 'visual.transformer.resblocks.8.ln_2.weight', 'visual.transformer.resblocks.8.ln_2.bias', 'visual.transformer.resblocks.9.attn.in_proj_weight', 'visual.transformer.resblocks.9.attn.in_proj_bias', 'visual.transformer.resblocks.9.attn.out_proj.weight', 'visual.transformer.resblocks.9.attn.out_proj.bias', 'visual.transformer.resblocks.9.ln_1.weight', 'visual.transformer.resblocks.9.ln_1.bias', 'visual.transformer.resblocks.9.mlp.c_fc.weight', 'visual.transformer.resblocks.9.mlp.c_fc.bias', 'visual.transformer.resblocks.9.mlp.c_proj.weight', 'visual.transformer.resblocks.9.mlp.c_proj.bias', 'visual.transformer.resblocks.9.ln_2.weight', 'visual.transformer.resblocks.9.ln_2.bias', 'visual.transformer.resblocks.10.attn.in_proj_weight', 'visual.transformer.resblocks.10.attn.in_proj_bias', 'visual.transformer.resblocks.10.attn.out_proj.weight', 'visual.transformer.resblocks.10.attn.out_proj.bias', 'visual.transformer.resblocks.10.ln_1.weight', 'visual.transformer.resblocks.10.ln_1.bias', 'visual.transformer.resblocks.10.mlp.c_fc.weight', 'visual.transformer.resblocks.10.mlp.c_fc.bias', 'visual.transformer.resblocks.10.mlp.c_proj.weight', 'visual.transformer.resblocks.10.mlp.c_proj.bias', 'visual.transformer.resblocks.10.ln_2.weight', 'visual.transformer.resblocks.10.ln_2.bias', 'visual.transformer.resblocks.11.attn.in_proj_weight', 'visual.transformer.resblocks.11.attn.in_proj_bias', 'visual.transformer.resblocks.11.attn.out_proj.weight', 'visual.transformer.resblocks.11.attn.out_proj.bias', 'visual.transformer.resblocks.11.ln_1.weight', 'visual.transformer.resblocks.11.ln_1.bias', 'visual.transformer.resblocks.11.mlp.c_fc.weight', 'visual.transformer.resblocks.11.mlp.c_fc.bias', 'visual.transformer.resblocks.11.mlp.c_proj.weight', 'visual.transformer.resblocks.11.mlp.c_proj.bias', 'visual.transformer.resblocks.11.ln_2.weight', 'visual.transformer.resblocks.11.ln_2.bias', 'visual.ln_post.weight', 'visual.ln_post.bias', 'transformer.resblocks.0.attn.in_proj_weight', 'transformer.resblocks.0.attn.in_proj_bias', 'transformer.resblocks.0.attn.out_proj.weight', 'transformer.resblocks.0.attn.out_proj.bias', 'transformer.resblocks.0.ln_1.weight', 'transformer.resblocks.0.ln_1.bias', 'transformer.resblocks.0.mlp.c_fc.weight', 'transformer.resblocks.0.mlp.c_fc.bias', 'transformer.resblocks.0.mlp.c_proj.weight', 'transformer.resblocks.0.mlp.c_proj.bias', 'transformer.resblocks.0.ln_2.weight', 'transformer.resblocks.0.ln_2.bias', 'transformer.resblocks.1.attn.in_proj_weight', 'transformer.resblocks.1.attn.in_proj_bias', 'transformer.resblocks.1.attn.out_proj.weight', 'transformer.resblocks.1.attn.out_proj.bias', 'transformer.resblocks.1.ln_1.weight', 'transformer.resblocks.1.ln_1.bias', 'transformer.resblocks.1.mlp.c_fc.weight', 'transformer.resblocks.1.mlp.c_fc.bias', 'transformer.resblocks.1.mlp.c_proj.weight', 'transformer.resblocks.1.mlp.c_proj.bias', 'transformer.resblocks.1.ln_2.weight', 'transformer.resblocks.1.ln_2.bias', 'transformer.resblocks.2.attn.in_proj_weight', 'transformer.resblocks.2.attn.in_proj_bias', 'transformer.resblocks.2.attn.out_proj.weight', 'transformer.resblocks.2.attn.out_proj.bias', 'transformer.resblocks.2.ln_1.weight', 'transformer.resblocks.2.ln_1.bias', 'transformer.resblocks.2.mlp.c_fc.weight', 'transformer.resblocks.2.mlp.c_fc.bias', 'transformer.resblocks.2.mlp.c_proj.weight', 'transformer.resblocks.2.mlp.c_proj.bias', 'transformer.resblocks.2.ln_2.weight', 'transformer.resblocks.2.ln_2.bias', 'transformer.resblocks.3.attn.in_proj_weight', 'transformer.resblocks.3.attn.in_proj_bias', 'transformer.resblocks.3.attn.out_proj.weight', 'transformer.resblocks.3.attn.out_proj.bias', 'transformer.resblocks.3.ln_1.weight', 'transformer.resblocks.3.ln_1.bias', 'transformer.resblocks.3.mlp.c_fc.weight', 'transformer.resblocks.3.mlp.c_fc.bias', 'transformer.resblocks.3.mlp.c_proj.weight', 'transformer.resblocks.3.mlp.c_proj.bias', 'transformer.resblocks.3.ln_2.weight', 'transformer.resblocks.3.ln_2.bias', 'transformer.resblocks.4.attn.in_proj_weight', 'transformer.resblocks.4.attn.in_proj_bias', 'transformer.resblocks.4.attn.out_proj.weight', 'transformer.resblocks.4.attn.out_proj.bias', 'transformer.resblocks.4.ln_1.weight', 'transformer.resblocks.4.ln_1.bias', 'transformer.resblocks.4.mlp.c_fc.weight', 'transformer.resblocks.4.mlp.c_fc.bias', 'transformer.resblocks.4.mlp.c_proj.weight', 'transformer.resblocks.4.mlp.c_proj.bias', 'transformer.resblocks.4.ln_2.weight', 'transformer.resblocks.4.ln_2.bias', 'transformer.resblocks.5.attn.in_proj_weight', 'transformer.resblocks.5.attn.in_proj_bias', 'transformer.resblocks.5.attn.out_proj.weight', 'transformer.resblocks.5.attn.out_proj.bias', 'transformer.resblocks.5.ln_1.weight', 'transformer.resblocks.5.ln_1.bias', 'transformer.resblocks.5.mlp.c_fc.weight', 'transformer.resblocks.5.mlp.c_fc.bias', 'transformer.resblocks.5.mlp.c_proj.weight', 'transformer.resblocks.5.mlp.c_proj.bias', 'transformer.resblocks.5.ln_2.weight', 'transformer.resblocks.5.ln_2.bias', 'transformer.resblocks.6.attn.in_proj_weight', 'transformer.resblocks.6.attn.in_proj_bias', 'transformer.resblocks.6.attn.out_proj.weight', 'transformer.resblocks.6.attn.out_proj.bias', 'transformer.resblocks.6.ln_1.weight', 'transformer.resblocks.6.ln_1.bias', 'transformer.resblocks.6.mlp.c_fc.weight', 'transformer.resblocks.6.mlp.c_fc.bias', 'transformer.resblocks.6.mlp.c_proj.weight', 'transformer.resblocks.6.mlp.c_proj.bias', 'transformer.resblocks.6.ln_2.weight', 'transformer.resblocks.6.ln_2.bias', 'transformer.resblocks.7.attn.in_proj_weight', 'transformer.resblocks.7.attn.in_proj_bias', 'transformer.resblocks.7.attn.out_proj.weight', 'transformer.resblocks.7.attn.out_proj.bias', 'transformer.resblocks.7.ln_1.weight', 'transformer.resblocks.7.ln_1.bias', 'transformer.resblocks.7.mlp.c_fc.weight', 'transformer.resblocks.7.mlp.c_fc.bias', 'transformer.resblocks.7.mlp.c_proj.weight', 'transformer.resblocks.7.mlp.c_proj.bias', 'transformer.resblocks.7.ln_2.weight', 'transformer.resblocks.7.ln_2.bias', 'transformer.resblocks.8.attn.in_proj_weight', 'transformer.resblocks.8.attn.in_proj_bias', 'transformer.resblocks.8.attn.out_proj.weight', 'transformer.resblocks.8.attn.out_proj.bias', 'transformer.resblocks.8.ln_1.weight', 'transformer.resblocks.8.ln_1.bias', 'transformer.resblocks.8.mlp.c_fc.weight', 'transformer.resblocks.8.mlp.c_fc.bias', 'transformer.resblocks.8.mlp.c_proj.weight', 'transformer.resblocks.8.mlp.c_proj.bias', 'transformer.resblocks.8.ln_2.weight', 'transformer.resblocks.8.ln_2.bias', 'transformer.resblocks.9.attn.in_proj_weight', 'transformer.resblocks.9.attn.in_proj_bias', 'transformer.resblocks.9.attn.out_proj.weight', 'transformer.resblocks.9.attn.out_proj.bias', 'transformer.resblocks.9.ln_1.weight', 'transformer.resblocks.9.ln_1.bias', 'transformer.resblocks.9.mlp.c_fc.weight', 'transformer.resblocks.9.mlp.c_fc.bias', 'transformer.resblocks.9.mlp.c_proj.weight', 'transformer.resblocks.9.mlp.c_proj.bias', 'transformer.resblocks.9.ln_2.weight', 'transformer.resblocks.9.ln_2.bias', 'transformer.resblocks.10.attn.in_proj_weight', 'transformer.resblocks.10.attn.in_proj_bias', 'transformer.resblocks.10.attn.out_proj.weight', 'transformer.resblocks.10.attn.out_proj.bias', 'transformer.resblocks.10.ln_1.weight', 'transformer.resblocks.10.ln_1.bias', 'transformer.resblocks.10.mlp.c_fc.weight', 'transformer.resblocks.10.mlp.c_fc.bias', 'transformer.resblocks.10.mlp.c_proj.weight', 'transformer.resblocks.10.mlp.c_proj.bias', 'transformer.resblocks.10.ln_2.weight', 'transformer.resblocks.10.ln_2.bias', 'transformer.resblocks.11.attn.in_proj_weight', 'transformer.resblocks.11.attn.in_proj_bias', 'transformer.resblocks.11.attn.out_proj.weight', 'transformer.resblocks.11.attn.out_proj.bias', 'transformer.resblocks.11.ln_1.weight', 'transformer.resblocks.11.ln_1.bias', 'transformer.resblocks.11.mlp.c_fc.weight', 'transformer.resblocks.11.mlp.c_fc.bias', 'transformer.resblocks.11.mlp.c_proj.weight', 'transformer.resblocks.11.mlp.c_proj.bias', 'transformer.resblocks.11.ln_2.weight', 'transformer.resblocks.11.ln_2.bias', 'token_embedding.weight', 'ln_final.weight', 'ln_final.bias'])`

while the weights required by the model are as follows：
`odict_keys(['backbone.class_embedding', 'backbone.positional_embedding', 'backbone.conv1.weight', 'backbone.ln_pre.weight', 'backbone.ln_pre.bias', 'backbone.transformer.temporal_cls_token', 'backbone.transformer.balance', 'backbone.transformer.resblocks.0.attn.in_proj_weight', 'backbone.transformer.resblocks.0.attn.in_proj_bias', 'backbone.transformer.resblocks.0.attn.out_proj.weight', 'backbone.transformer.resblocks.0.attn.out_proj.bias', 'backbone.transformer.resblocks.0.ln_1.weight', 'backbone.transformer.resblocks.0.ln_1.bias', 'backbone.transformer.resblocks.0.mlp.c_fc.weight', 'backbone.transformer.resblocks.0.mlp.c_fc.bias', 'backbone.transformer.resblocks.0.mlp.c_proj.weight', 'backbone.transformer.resblocks.0.mlp.c_proj.bias', 'backbone.transformer.resblocks.0.ln_2.weight', 'backbone.transformer.resblocks.0.ln_2.bias', 'backbone.transformer.resblocks.1.attn.in_proj_weight', 'backbone.transformer.resblocks.1.attn.in_proj_bias', 'backbone.transformer.resblocks.1.attn.out_proj.weight', 'backbone.transformer.resblocks.1.attn.out_proj.bias', 'backbone.transformer.resblocks.1.ln_1.weight', 'backbone.transformer.resblocks.1.ln_1.bias', 'backbone.transformer.resblocks.1.mlp.c_fc.weight', 'backbone.transformer.resblocks.1.mlp.c_fc.bias', 'backbone.transformer.resblocks.1.mlp.c_proj.weight', 'backbone.transformer.resblocks.1.mlp.c_proj.bias', 'backbone.transformer.resblocks.1.ln_2.weight', 'backbone.transformer.resblocks.1.ln_2.bias', 'backbone.transformer.resblocks.2.attn.in_proj_weight', 'backbone.transformer.resblocks.2.attn.in_proj_bias', 'backbone.transformer.resblocks.2.attn.out_proj.weight', 'backbone.transformer.resblocks.2.attn.out_proj.bias', 'backbone.transformer.resblocks.2.ln_1.weight', 'backbone.transformer.resblocks.2.ln_1.bias', 'backbone.transformer.resblocks.2.mlp.c_fc.weight', 'backbone.transformer.resblocks.2.mlp.c_fc.bias', 'backbone.transformer.resblocks.2.mlp.c_proj.weight', 'backbone.transformer.resblocks.2.mlp.c_proj.bias', 'backbone.transformer.resblocks.2.ln_2.weight', 'backbone.transformer.resblocks.2.ln_2.bias', 'backbone.transformer.resblocks.3.attn.in_proj_weight', 'backbone.transformer.resblocks.3.attn.in_proj_bias', 'backbone.transformer.resblocks.3.attn.out_proj.weight', 'backbone.transformer.resblocks.3.attn.out_proj.bias', 'backbone.transformer.resblocks.3.ln_1.weight', 'backbone.transformer.resblocks.3.ln_1.bias', 'backbone.transformer.resblocks.3.mlp.c_fc.weight', 'backbone.transformer.resblocks.3.mlp.c_fc.bias', 'backbone.transformer.resblocks.3.mlp.c_proj.weight', 'backbone.transformer.resblocks.3.mlp.c_proj.bias', 'backbone.transformer.resblocks.3.ln_2.weight', 'backbone.transformer.resblocks.3.ln_2.bias', 'backbone.transformer.resblocks.4.attn.in_proj_weight', 'backbone.transformer.resblocks.4.attn.in_proj_bias', 'backbone.transformer.resblocks.4.attn.out_proj.weight', 'backbone.transformer.resblocks.4.attn.out_proj.bias', 'backbone.transformer.resblocks.4.ln_1.weight', 'backbone.transformer.resblocks.4.ln_1.bias', 'backbone.transformer.resblocks.4.mlp.c_fc.weight', 'backbone.transformer.resblocks.4.mlp.c_fc.bias', 'backbone.transformer.resblocks.4.mlp.c_proj.weight', 'backbone.transformer.resblocks.4.mlp.c_proj.bias', 'backbone.transformer.resblocks.4.ln_2.weight', 'backbone.transformer.resblocks.4.ln_2.bias', 'backbone.transformer.resblocks.5.attn.in_proj_weight', 'backbone.transformer.resblocks.5.attn.in_proj_bias', 'backbone.transformer.resblocks.5.attn.out_proj.weight', 'backbone.transformer.resblocks.5.attn.out_proj.bias', 'backbone.transformer.resblocks.5.ln_1.weight', 'backbone.transformer.resblocks.5.ln_1.bias', 'backbone.transformer.resblocks.5.mlp.c_fc.weight', 'backbone.transformer.resblocks.5.mlp.c_fc.bias', 'backbone.transformer.resblocks.5.mlp.c_proj.weight', 'backbone.transformer.resblocks.5.mlp.c_proj.bias', 'backbone.transformer.resblocks.5.ln_2.weight', 'backbone.transformer.resblocks.5.ln_2.bias', 'backbone.transformer.resblocks.6.attn.in_proj_weight', 'backbone.transformer.resblocks.6.attn.in_proj_bias', 'backbone.transformer.resblocks.6.attn.out_proj.weight', 'backbone.transformer.resblocks.6.attn.out_proj.bias', 'backbone.transformer.resblocks.6.ln_1.weight', 'backbone.transformer.resblocks.6.ln_1.bias', 'backbone.transformer.resblocks.6.mlp.c_fc.weight', 'backbone.transformer.resblocks.6.mlp.c_fc.bias', 'backbone.transformer.resblocks.6.mlp.c_proj.weight', 'backbone.transformer.resblocks.6.mlp.c_proj.bias', 'backbone.transformer.resblocks.6.ln_2.weight', 'backbone.transformer.resblocks.6.ln_2.bias', 'backbone.transformer.resblocks.7.attn.in_proj_weight', 'backbone.transformer.resblocks.7.attn.in_proj_bias', 'backbone.transformer.resblocks.7.attn.out_proj.weight', 'backbone.transformer.resblocks.7.attn.out_proj.bias', 'backbone.transformer.resblocks.7.ln_1.weight', 'backbone.transformer.resblocks.7.ln_1.bias', 'backbone.transformer.resblocks.7.mlp.c_fc.weight', 'backbone.transformer.resblocks.7.mlp.c_fc.bias', 'backbone.transformer.resblocks.7.mlp.c_proj.weight', 'backbone.transformer.resblocks.7.mlp.c_proj.bias', 'backbone.transformer.resblocks.7.ln_2.weight', 'backbone.transformer.resblocks.7.ln_2.bias', 'backbone.transformer.resblocks.8.attn.in_proj_weight', 'backbone.transformer.resblocks.8.attn.in_proj_bias', 'backbone.transformer.resblocks.8.attn.out_proj.weight', 'backbone.transformer.resblocks.8.attn.out_proj.bias', 'backbone.transformer.resblocks.8.ln_1.weight', 'backbone.transformer.resblocks.8.ln_1.bias', 'backbone.transformer.resblocks.8.mlp.c_fc.weight', 'backbone.transformer.resblocks.8.mlp.c_fc.bias', 'backbone.transformer.resblocks.8.mlp.c_proj.weight', 'backbone.transformer.resblocks.8.mlp.c_proj.bias', 'backbone.transformer.resblocks.8.ln_2.weight', 'backbone.transformer.resblocks.8.ln_2.bias', 'backbone.transformer.resblocks.9.attn.in_proj_weight', 'backbone.transformer.resblocks.9.attn.in_proj_bias', 'backbone.transformer.resblocks.9.attn.out_proj.weight', 'backbone.transformer.resblocks.9.attn.out_proj.bias', 'backbone.transformer.resblocks.9.ln_1.weight', 'backbone.transformer.resblocks.9.ln_1.bias', 'backbone.transformer.resblocks.9.mlp.c_fc.weight', 'backbone.transformer.resblocks.9.mlp.c_fc.bias', 'backbone.transformer.resblocks.9.mlp.c_proj.weight', 'backbone.transformer.resblocks.9.mlp.c_proj.bias', 'backbone.transformer.resblocks.9.ln_2.weight', 'backbone.transformer.resblocks.9.ln_2.bias', 'backbone.transformer.resblocks.10.attn.in_proj_weight', 'backbone.transformer.resblocks.10.attn.in_proj_bias', 'backbone.transformer.resblocks.10.attn.out_proj.weight', 'backbone.transformer.resblocks.10.attn.out_proj.bias', 'backbone.transformer.resblocks.10.ln_1.weight', 'backbone.transformer.resblocks.10.ln_1.bias', 'backbone.transformer.resblocks.10.mlp.c_fc.weight', 'backbone.transformer.resblocks.10.mlp.c_fc.bias', 'backbone.transformer.resblocks.10.mlp.c_proj.weight', 'backbone.transformer.resblocks.10.mlp.c_proj.bias', 'backbone.transformer.resblocks.10.ln_2.weight', 'backbone.transformer.resblocks.10.ln_2.bias', 'backbone.transformer.resblocks.11.attn.in_proj_weight', 'backbone.transformer.resblocks.11.attn.in_proj_bias', 'backbone.transformer.resblocks.11.attn.out_proj.weight', 'backbone.transformer.resblocks.11.attn.out_proj.bias', 'backbone.transformer.resblocks.11.ln_1.weight', 'backbone.transformer.resblocks.11.ln_1.bias', 'backbone.transformer.resblocks.11.mlp.c_fc.weight', 'backbone.transformer.resblocks.11.mlp.c_fc.bias', 'backbone.transformer.resblocks.11.mlp.c_proj.weight', 'backbone.transformer.resblocks.11.mlp.c_proj.bias', 'backbone.transformer.resblocks.11.ln_2.weight', 'backbone.transformer.resblocks.11.ln_2.bias', 'backbone.transformer.dpe.0.weight', 'backbone.transformer.dpe.0.bias', 'backbone.transformer.dpe.1.weight', 'backbone.transformer.dpe.1.bias', 'backbone.transformer.dpe.2.weight', 'backbone.transformer.dpe.2.bias', 'backbone.transformer.dpe.3.weight', 'backbone.transformer.dpe.3.bias', 'backbone.transformer.dec.0.attn.in_proj_weight', 'backbone.transformer.dec.0.attn.in_proj_bias', 'backbone.transformer.dec.0.attn.out_proj.weight', 'backbone.transformer.dec.0.attn.out_proj.bias', 'backbone.transformer.dec.0.ln_1.weight', 'backbone.transformer.dec.0.ln_1.bias', 'backbone.transformer.dec.0.mlp.c_fc.weight', 'backbone.transformer.dec.0.mlp.c_fc.bias', 'backbone.transformer.dec.0.mlp.c_proj.weight', 'backbone.transformer.dec.0.mlp.c_proj.bias', 'backbone.transformer.dec.0.ln_2.weight', 'backbone.transformer.dec.0.ln_2.bias', 'backbone.transformer.dec.0.ln_3.weight', 'backbone.transformer.dec.0.ln_3.bias', 'backbone.transformer.dec.1.attn.in_proj_weight', 'backbone.transformer.dec.1.attn.in_proj_bias', 'backbone.transformer.dec.1.attn.out_proj.weight', 'backbone.transformer.dec.1.attn.out_proj.bias', 'backbone.transformer.dec.1.ln_1.weight', 'backbone.transformer.dec.1.ln_1.bias', 'backbone.transformer.dec.1.mlp.c_fc.weight', 'backbone.transformer.dec.1.mlp.c_fc.bias', 'backbone.transformer.dec.1.mlp.c_proj.weight', 'backbone.transformer.dec.1.mlp.c_proj.bias', 'backbone.transformer.dec.1.ln_2.weight', 'backbone.transformer.dec.1.ln_2.bias', 'backbone.transformer.dec.1.ln_3.weight', 'backbone.transformer.dec.1.ln_3.bias', 'backbone.transformer.dec.2.attn.in_proj_weight', 'backbone.transformer.dec.2.attn.in_proj_bias', 'backbone.transformer.dec.2.attn.out_proj.weight', 'backbone.transformer.dec.2.attn.out_proj.bias', 'backbone.transformer.dec.2.ln_1.weight', 'backbone.transformer.dec.2.ln_1.bias', 'backbone.transformer.dec.2.mlp.c_fc.weight', 'backbone.transformer.dec.2.mlp.c_fc.bias', 'backbone.transformer.dec.2.mlp.c_proj.weight', 'backbone.transformer.dec.2.mlp.c_proj.bias', 'backbone.transformer.dec.2.ln_2.weight', 'backbone.transformer.dec.2.ln_2.bias', 'backbone.transformer.dec.2.ln_3.weight', 'backbone.transformer.dec.2.ln_3.bias', 'backbone.transformer.dec.3.attn.in_proj_weight', 'backbone.transformer.dec.3.attn.in_proj_bias', 'backbone.transformer.dec.3.attn.out_proj.weight', 'backbone.transformer.dec.3.attn.out_proj.bias', 'backbone.transformer.dec.3.ln_1.weight', 'backbone.transformer.dec.3.ln_1.bias', 'backbone.transformer.dec.3.mlp.c_fc.weight', 'backbone.transformer.dec.3.mlp.c_fc.bias', 'backbone.transformer.dec.3.mlp.c_proj.weight', 'backbone.transformer.dec.3.mlp.c_proj.bias', 'backbone.transformer.dec.3.ln_2.weight', 'backbone.transformer.dec.3.ln_2.bias', 'backbone.transformer.dec.3.ln_3.weight', 'backbone.transformer.dec.3.ln_3.bias', 'backbone.transformer.proj.0.weight', 'backbone.transformer.proj.0.bias', 'backbone.transformer.proj.2.weight', 'backbone.transformer.proj.2.bias'])`

**Comment by Andy1621** [comment]
Thanks for your question. In my codebase, the model is packed by class `Uniformerv2`, so the weights have the prefix `backbone.`
https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/slowfast/models/uniformerv2.py#L45-L64

For the ViT model, it seems that you try to load CLIP pretrained ViT. Please follow the [jupyter script](https://github.com/OpenGVLab/UniFormerV2/blob/main/extract_clip/extract.ipynb) to load the pretrained visual encoder. 
![image](https://user-images.githubusercontent.com/24236723/205938505-c8624dbb-0f5f-4a90-b60b-6583b480e5c8.png)
For loading models, you can find the code as follows,
https://github.com/OpenGVLab/UniFormerV2/blob/d390105e588665af5029bfcceed5b9975d4b13bb/slowfast/models/uniformerv2_model.py#L333-L356

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
